### ISSUE TITLE
Cannot view or install GOG games

### ISSUE THREAD

**Issue by riksweeney** [Heroic-Games-Launcher/HeroicGamesLauncher#1489]
### Describe the bug

My GOG games are listed in my library as expected. When I click on a game however, the game's info appears for a split second before the message "Cannot get game info" appears in the right side panel.

Please see the attached log file.

I have tried signing in out and a few times to no avail. From the looks of things, the JSON has either changed or is broken on GOG's end.

### Add logs

(09:56:38) INFO:    [Gog]:             Getting game metadata: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl info 1136126792 --token <redacted> --lang=en-US --os windows
(09:56:38) DEBUG:   [Gog]:             Running GOGDL command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl info 1136126792 --token <redacted> --lang=en-US --os windows
(09:56:39) ERROR:   [Backend]:         SyntaxError: Unexpected end of JSON input
(09:56:39) ERROR:   [Frontend]:        Cannot get game info

### Steps to reproduce

Sign into GOG and ensure games from your GOG account are listed in your library.
Click on one of the GOG games to view its information.
The game's information will appear briefly and is then replaced with the error message described.

### Expected behavior

The user should be able to view and install GOG games.

### System Information

  Heroic Version: 2.3.2 Brook
  Legendary Version:  0.20.25 Our Benefactors
  OS: Ubuntu KERNEL: 5.4.0-120-generic ARCH: x64
  CPU: Intel Core™ i5-5200U @2.2 GOVERNOR: powersave
  RAM: Total: 7.68 GiB Available: 1.52 GiB
  GRAPHICS: GPU0: HD Graphics 5500  VRAM: 256MB DRIVER:  GPU1: GK208BM [GeForce 920M]  VRAM: 32MB DRIVER:  
  PROTOCOL: x11

**Comment by yoshimo** [comment]
2.3.9 is the current stable version. Try to update

**Comment by flavioislima** [comment]
Yes, this issue was fixed sometime ago I believe. After updating it go to settings > Advanced > Clear Cache.

**Comment by riksweeney** [comment]
Thanks, I've updated but only the first GOG game I tried to view worked. After that every GOG game produced the error message described above (the game info appears fleetingly before being replaced). Clearing the cache doesn't appear to solve the problem, neither does resetting Heroic.

Where are Heroic's settings stored? I'll manually delete them and see if that helps matters.

**Comment by flavioislima** [comment]
at `~/.config/heroic`.

Have you also tried log out and in again, right?
Which ubuntu is that?

**Comment by riksweeney** [comment]
I'm on Ubuntu 18.04.6 LTS, so pretty old.

Unfortunately, I've deleted the settings, restarted my system and also reinstalled Heroic from scratch but have the same result. I will continue to do some digging and see if I can pin it down a bit more.

**Comment by imLinguin** [comment]
We had some issues reported for gogdl. I guess I'll switch workflows to use Ubuntu 18 instead of latest one.

**Comment by arielj** [comment]
Can you try running the gogdl command manually? looks like the output is not a valid JSON

First go to Heroic's config folder, look for this file: `~/.config/heroic/gog_store/config.json`. Open the file in a text editor, you should have a lot info, look for this `"access_token": "12345..."` should be close to the top. Copy that token (in my example, select and copy `"12345..."`, including the quotes character

Now open a terminal and run this command:

```
/opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl info 1136126792 --token "12345..." --lang=en-US --os windows
```

> Note that I put the access token there inside the command after `--token`

**Comment by riksweeney** [comment]
Here's the output:

[2359] Error loading Python lib '/tmp/_MEINt84OL/libpython3.9.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/_MEINt84OL/libpython3.9.so.1.0)

I guess my system might be a bit too old

**Comment by imLinguin** [comment]
Like I said I'll try changing the system version in the workflow and get you updated.

**Comment by flavioislima** [comment]
Actually, we cannot support such an old system, that would be complicated for us. We need at least the latest Ubuntu LTS.
We will update the Readme with the supported Linux distros and versions.

**Comment by riksweeney** [comment]
Sorry for the delay in my reply, I was on holiday.

No worries, thanks for having a look into it anyway. My machine is getting a bit long in the tooth now so I really should upgrade both it and the OS!
