### ISSUE TITLE
Some games automatically cancel their installations while downloading.

### ISSUE THREAD

**Issue by benthetechguy** [Heroic-Games-Launcher/HeroicGamesLauncher#195]
**Describe the bug**
Some games' downloads cancel themselves after a few minutes of downloading (doesn't happen on every game, seemingly at random)

**To Reproduce**
Attempt to download a game and watch as the install is (sometimes) cancelled automatically after roughly 10 minutes.

**Expected behavior**
Games should reach 100% download and successfully install.

**Desktop (please complete the following information):**
 - OS: Manjaro
-  Game: GTA V, Metro Last Light Redux, Rocket League, several others

**Comment by flavioislima** [comment]
Try increasing the amount of workers on settings and download again.

**Comment by koltasaurusrex** [comment]
Same problem. Increased workers to max amount and Rage 2 still cancels install around 40%. 

Manjaro

**Comment by flavioislima** [comment]
Can you try download those games with legendary? Because heroic just send the command for it to download so if with legendary it works then I'll try to find something on heroic because I cannot reproduce it. Downloaded rage 2 yesterday and it was OK. Even putting heroic on the tray it works for me.

Also, can you run heroic from terminal and see if it shows any error message while downloading?

**Comment by koltasaurusrex** [comment]
Switched to legendary and continued the download pointing it to heroics game directory and the download completed. It resumed what had been downloaded from heroic which was great and then the remaining download speed was about twice as fast as what heroic showed for some reason. I didn't see your comment before about using heroic in terminal, I'll try another game to see if it hangs then test through the terminal.

**Comment by benthetechguy** [comment]
> Can you run heroic from terminal and see if it shows any error message while downloading?

Will do

> Can you try download those games with legendary?

I'll do that if increasing the workers doesn't work.

**Comment by GrabowskiDev** [comment]
I have the same problem, Borderlands 3 usually cancel downloading after around 38GiB of downloaded data. I have the maximum amount of workers (4) and still getting this error

**Comment by flavioislima** [comment]
@GrabowskiDev have you tried with legendary? 

Even though I could not replicate the issue, I sent a change yesterday to the main branch with some changes on the workers part adding a max option. If that's the issue, using max should work.

It will be available on next release.

**Comment by adityaruplaha** [comment]
Any updates on this issue? Some other users reported similar behaviour too.

**Comment by BiRo96** [comment]
@flavioislima i had the same issue with GTA V yesterday 3 tines in a row, still not having it downloaded :/
I guess it depends on the speed of internet and the size of the game (105GB in my case)

**Comment by jarrard** [comment]
Yeah I get this issue happening randomly, it needs to auto resume if the user didn't directly cancel the download. (or pause)

**Comment by GM-Script-Writer-62850** [comment]
check your network usage when this happens, for me the game was downloading but the UI was not updating the percentage, by waiting for network usage to drop and restarting the launcher the game showed 100% and was ready to launch

**Comment by 492citizen** [comment]
I am experiencing the same Issue as well with The Outer Worlds. The download just cancels at about 30 or 40 percent.

**Comment by spider3000** [comment]
Just stumbled upon this issue. I've had the same problem as well with Killing Floor 2 yesterday. However I see using ps that there are multiple legendary threads running and I assume still downloading, because my network speed hadn't recovered.
I assume Heroic somehow loses connection to the progress of legendary.

**Comment by DuttaAB-dev** [comment]
Faced the same issue while trying to download GTA V, the launcher suddenly prompted that the installation was cancelled. But noticed my network downloads to be active and at full speed. Waited for a few hours and sure enough the game had been downloaded and was ready to play.

**Comment by adityaruplaha** [comment]
The issue is that Heroic loses track of Legendary's progress. While we know where the issue is, we don't know why this happens.

Also, we have plans to refactor this code which might fix the issue, but all of us are currently engaged in other projects. 

Here's a synopsis:
Our current implementation of `requestGameProgress` is hot garbage. It's unreliable and extremely finicky. It currently reads the last few lines of the log file and tries to figure out what the progress is. Sometimes it fails miserably. We plan to replace it with a socket/regex based system, but haven't gotten around to doing it yet.

So if anyone is willing to put the time into fixing this, it'll be much appreciated.

**Comment by flavioislima** [comment]
@DuttaAB-dev @BiRo96 @spider3000 @492citizen 
can you guys try to replicate the issue with this test version:
https://drive.google.com/file/d/1tfyVw4ytzHCjlC3fuOaQrt_V8ak-y4cr/view?usp=sharing
?

Thanks

**Comment by DuttaAB-dev** [comment]
> @DuttaAB-dev @BiRo96 @spider3000 @492citizen 
> can you guys try to replicate the issue with this test version:
> https://drive.google.com/file/d/1tfyVw4ytzHCjlC3fuOaQrt_V8ak-y4cr/view?usp=sharing
> ?
> 
> Thanks

Issue still persists. Stopped reporting progress after about 27% completion of GTA V. Same as before, said download cancelled even when legendary was downloading it in the background.

**Comment by adityaruplaha** [comment]
Welp it's almost certainly my code then. I still have no idea what's happening.

**Comment by adityaruplaha** [comment]
From #277: some games don't cancel the installation, but progress freezes.

**Comment by debiangamer** [comment]
Inspect the code where heroic calls notifyd.

**Comment by adityaruplaha** [comment]
Well I know that this happens when Heroic loses track of Legendary's progress, but no idea why that happens.

**Comment by debiangamer** [comment]
Have you enabled logging in notifyd? What the notifyd log shows?

**Comment by flavioislima** [comment]
> Inspect the code where heroic calls notifyd when downloading a game.

This is related with the notification.
So its called after the download is interrupted.

**Comment by flavioislima** [comment]
> Thanks



> Have you enabled logging in notifyd? What the notifyd log shows? Those notifyd messages comes from this code:
> 
> ```
> const progress = await renderer.invoke('requestGameProgress', appName)
>       const percent = getProgress(progress)
> 
>       if (percent) {
>         const message =
>           percent < 95
>             ? t('notify.install.canceled')
>             : t('notify.install.finished')
>         notify([title, message])
>         return this.refreshLibrary()
>       }
>       this.refreshLibrary()
>       return notify([title, 'Game Imported
> ```
> 
> There are these messages when notifyd is running and the heroic believes that installing fails:
> operation interrupted
> finished installing
> 
> You must inspect what leads to operation interrupted situation and improve error handling. A 5 GB game did install fine, but not 20 GB. Memory handling problems?
> 
> ```
> async function errorHandler(logPath: string): Promise<void> {
>   const noSpaceMsg = 'Not enough available disk space'
>   return execAsync(`tail ${logPath} | grep 'disk space'`)
>     .then(({ stdout }) => {
>       if (stdout.includes(noSpaceMsg)) {
>         console.log(noSpaceMsg)
>         return showErrorBox(
>           i18next.t('box.error.diskspace.title', 'No Space'),
>           i18next.t(
>             'box.error.diskspace.message',
>             'Not enough available disk space'
>           )
>         )
>       }
>       return genericErrorMessage()
>     })
>     .catch(() => console.log('operation interrupted'))
> }
> ```

I don't know. The first code is from the frontend and the second from the backend.
At first, I was thinking the issue would be with the progress function but the thing is that It is used only when Heroic detects the legendary process. If it loses connection, it thinks that the process was killed.

So, after some digging, I bet the issue was introduced on 1.5+ version, and looking at the install function, I noticed we did some changes there.

Now, I reverted those changes and generated a deb and an AppImage file for testing.
If this doesn't fixes, I have no idea what will.
because I installed Ubuntu and PopOs on my machine, along with Garuda that is my main OS and this never ever happened to me so it is really hard to fix a bug that we cannot replicate.

I think might be a memory issue but at the same time. Heroic is using only 100MB of ram on Garuda and 120MB on PopOS.
Might be that the app is going to sleep mode as well but we have a function to prevent sleep while downloading, verifying or updating a game.

Anyway, here is the new test version:
https://drive.google.com/drive/folders/1OaxxUQENLwQ-XgQVFrEuyjtmAIvBJ0jl?usp=sharing

I appreciate if you guys could try and give me more feedback.
If you guys could also try version 1.4 would be nice, but I recommend making a backup of your `.config/legendary` and `.config/heroic` folders before trying an older version since you might have some conflicts with the config file.

**Comment by debiangamer** [comment]
Can you put a parameter to .catch(()  to get more  information what happened?

**Comment by flavioislima** [comment]
> Can you put a parameter to .catch(() to get more information what happened?

I added a console.log on the catch on this latest test. So should appear more info now.

**Comment by GM-Script-Writer-62850** [comment]
> ```
> const progress = await renderer.invoke('requestGameProgress', appName)
>       const percent = getProgress(progress)
> 
>       if (percent) {
>         const message =
>           percent < 95
>             ? t('notify.install.canceled')
>             : t('notify.install.finished')
>         notify([title, message])
>         return this.refreshLibrary()
>       }
>       this.refreshLibrary()
>       return notify([title, 'Game Imported
> ```

My guess is percent is NaN when it breaks
i would suggest checking if NaN and having it try to read the percent again after say 0.05 seconds, if that happens over say 10 times in a row there is a problem
My theory is when it reads the file the data is being written and it can't get it cause it is in the process of being overwritten, this is a issue i have had even when using RAM as a disk, admittedly it took months actually error in a process that runs 24/7

**Comment by flavioislima** [comment]
> > ```
> > const progress = await renderer.invoke('requestGameProgress', appName)
> >       const percent = getProgress(progress)
> > 
> >       if (percent) {
> >         const message =
> >           percent < 95
> >             ? t('notify.install.canceled')
> >             : t('notify.install.finished')
> >         notify([title, message])
> >         return this.refreshLibrary()
> >       }
> >       this.refreshLibrary()
> >       return notify([title, 'Game Imported
> > ```
> 
> My guess is percent is NaN when it breaks
> i would suggest checking if NaN and having it try to read the percent again after say 0.05 seconds, if that happens over say 10 times in a row there is a problem
> My theory is when it reads the file the data is being written and it can't get it cause it is in the process of being overwritten, this is a issue i have had even when using RAM as a disk, admittedly it took months to actually error in a process that runs 24/7 updating every 2 to 3 seconds

I see your point. In the test versions I sent above, a added a handler to when we get no percent or no info at all from the file, so it should work. But since I didn't, now I'm trying to check if the error is on the install function. That's my latest guess.

**Comment by GM-Script-Writer-62850** [comment]
anyway if my theory is right, you can increase the odds of the issue occurring by doing this
* Using a game that takes a LONG time to download (eg: COD or GTA5)
* Using a slow drive to hold the progress file (like a garbage tear flash drive or a floppy disk)
* slamming a not slow device with more work to it takes longer to update the progress file

**Comment by flavioislima** [comment]
> anyway if my theory is right, you can increase the odds of the issue occurring by doing this
> 
>     * Using a game that takes a LONG time to download (eg: COD or GTA5)
> 
>     * Using a slow drive to hold the progress file (like a garbage tear flash drive or a floppy disk)
> 
>     * slamming a not slow device with more work to it takes longer to update the progress file

I tried using an HDD and a FlashDrive yesterday, and it was the same. The thing is that I don't have a really slow device with me.
My USB flash drive is USB3 and my HDD is a new one Seagate Barracuda, other than that I have only SSD Sata and NVME.
I tried to replicate the issue on other distros but with no success. Now I'm setting up a VM with just 4GB of ram with Ubuntu to see if it is a memory issue.

**Comment by flavioislima** [comment]
@debiangamer @benthetechguy @spider3000 @jarrard @BiRo96 @DuttaAB-dev 
Whats your hardware specs by the way?
Memory and internet speed. 
Are you guys using the home folder on an HDD or SSD?

Thanks

**Comment by debiangamer** [comment]
```
System:
  Host: optipc Kernel: 5.13.0-rc2 x86_64 bits: 64 Desktop: Xfce 4.16.0 
  Distro: Debian GNU/Linux 11 (bullseye) 
Machine:
  Type: Desktop Mobo: ASUSTeK model: PRIME B450M-K v: Rev X.0x 
  serial: <superuser required> UEFI: American Megatrends v: 3002 
  date: 03/11/2021 
CPU:
  Info: 6-Core AMD Ryzen 5 2600 [MT MCP] speed: 1371 MHz 
  min/max: 1550/3400 MHz 
Graphics:
  Device-1: AMD Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] 
  driver: amdgpu v: kernel 
  Device-2: GEMBIRD Generic UVC 1.00 camera [AppoTech AX2311] type: USB 
  driver: uvcvideo 
  Display: x11 server: X.Org 1.20.11 driver: loaded: amdgpu 
  resolution: 3840x2160~60Hz 
  OpenGL: renderer: Radeon RX 580 Series (POLARIS10 DRM 3.41.0 5.13.0-rc2 
  LLVM 12.0.0) 
  v: 4.6 Mesa 21.2.0-devel (git-0df249f 2021-05-19 focal-oibaf-ppa) 
```
The download failed in 16.22% with the Close to the Sun game that is 20 GB.
```
    '[DLManager] INFO:  - Downloaded: 3738.65 MiB, Written: 3817.30 MiB\n' +
      '[DLManager] INFO:  - Cache usage: 58.0 MiB, active tasks: 32\n' +
      '[DLManager] INFO:  + Download\t- 1.00 MiB/s (raw) / 1.00 MiB/s (decompressed)\n' +
      '[DLManager] INFO:  + Disk\t- 7.99 MiB/s (write) / 0.00 MiB/s (read)\n' +
      '[DLManager] INFO: = Progress: 16.18% (3913/24179), Running for 00:48:47, ETA: 04:12:40\n' +
      '[DLManager] INFO:  - Downloaded: 3739.65 MiB, Written: 3817.30 MiB\n' +
      '[DLManager] INFO:  - Cache usage: 59.0 MiB, active tasks: 32\n' +
      '[DLManager] INFO:  + Download\t- 1.00 MiB/s (raw) / 1.00 MiB/s (decompressed)\n' +
      '[DLManager] INFO:  + Disk\t- 0.00 MiB/s (write) / 0.00 MiB/s (read)\n' +
      '[DLManager] INFO: = Progress: 16.18% (3913/24179), Running for 00:48:48, ETA: 04:12:45\n' +
      '[DLManager] INFO:  - Downloaded: 3741.64 MiB, Written: 3817.30 MiB\n' +
      '[DLManager] INFO:  - Cache usage: 61.0 MiB, active tasks: 32\n' +
      '[DLManager] INFO:  + Download\t- 1.99 MiB/s (raw) / 2.00 MiB/s (decompressed)\n' +
      '[DLManager] INFO:  + Disk\t- 0.00 MiB/s (write) / 0.00 MiB/s (read)\n' +
      '[DLManager] INFO: = Progress: 16.20% (3918/24179), Running for 00:48:49, ETA: 04:12:28\n' +
      '[DLManager] INFO:  - Downloaded: 3744.62 MiB, Written: 3822.30 MiB\n' +
      '[DLManager] INFO:  - Cache usage: 59.0 MiB, active tasks: 32\n' +
      '[DLManager] INFO:  + Download\t- 2.98 MiB/s (raw) / 3.00 MiB/s (decompressed)\n' +
      '[DLManager] INFO:  + Disk\t- 4.99 MiB/s (write) / 0.00 MiB/s (read)\n' +
      '[DLManager] INFO: = Progress: 16.22% (3921/24179), Running for 00:48:50, ETA: 04:12:19\n' +
      '[DLManager] INFO:  - Downloaded: 3745.62 MiB, Written: 3825.30 MiB\n' +
      '[DLManager] INFO:  - Cac',
    stderr: ''
  }
}
finished installing
Progress: Silene 16.22%/3745.62
MiB/04:12:19

```

**Comment by GM-Script-Writer-62850** [comment]
When i had this occur this was my drive config using GTA5 IRC this was like 50-70% done
* 120GB SSD Boot
* 500gb HDD Home (WD Blue 7200RPM)
* 1TB HDD storage (WD Blue 7200RPM)
* 16GB RAM DDR4 dual channel (set at  3200 c16 to 3800 cl 18)
* Net is 100/10 Mbps

**Comment by adityaruplaha** [comment]
> ```
> System:
>   Host: optipc Kernel: 5.13.0-rc2 x86_64 bits: 64 Desktop: Xfce 4.16.0 
>   Distro: Debian GNU/Linux 11 (bullseye) 
> Machine:
>   Type: Desktop Mobo: ASUSTeK model: PRIME B450M-K v: Rev X.0x 
>   serial: <superuser required> UEFI: American Megatrends v: 3002 
>   date: 03/11/2021 
> CPU:
>   Info: 6-Core AMD Ryzen 5 2600 [MT MCP] speed: 1371 MHz 
>   min/max: 1550/3400 MHz 
> Graphics:
>   Device-1: AMD Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] 
>   driver: amdgpu v: kernel 
>   Device-2: GEMBIRD Generic UVC 1.00 camera [AppoTech AX2311] type: USB 
>   driver: uvcvideo 
>   Display: x11 server: X.Org 1.20.11 driver: loaded: amdgpu 
>   resolution: 3840x2160~60Hz 
>   OpenGL: renderer: Radeon RX 580 Series (POLARIS10 DRM 3.41.0 5.13.0-rc2 
>   LLVM 12.0.0) 
>   v: 4.6 Mesa 21.2.0-devel (git-0df249f 2021-05-19 focal-oibaf-ppa) 
> ```
> The download failed in 16.22% with the Close to the Sun game that is 20 GB.
> ```
>     '[DLManager] INFO:  - Downloaded: 3738.65 MiB, Written: 3817.30 MiB\n' +
>       '[DLManager] INFO:  - Cache usage: 58.0 MiB, active tasks: 32\n' +
>       '[DLManager] INFO:  + Download\t- 1.00 MiB/s (raw) / 1.00 MiB/s (decompressed)\n' +
>       '[DLManager] INFO:  + Disk\t- 7.99 MiB/s (write) / 0.00 MiB/s (read)\n' +
>       '[DLManager] INFO: = Progress: 16.18% (3913/24179), Running for 00:48:47, ETA: 04:12:40\n' +
>       '[DLManager] INFO:  - Downloaded: 3739.65 MiB, Written: 3817.30 MiB\n' +
>       '[DLManager] INFO:  - Cache usage: 59.0 MiB, active tasks: 32\n' +
>       '[DLManager] INFO:  + Download\t- 1.00 MiB/s (raw) / 1.00 MiB/s (decompressed)\n' +
>       '[DLManager] INFO:  + Disk\t- 0.00 MiB/s (write) / 0.00 MiB/s (read)\n' +
>       '[DLManager] INFO: = Progress: 16.18% (3913/24179), Running for 00:48:48, ETA: 04:12:45\n' +
>       '[DLManager] INFO:  - Downloaded: 3741.64 MiB, Written: 3817.30 MiB\n' +
>       '[DLManager] INFO:  - Cache usage: 61.0 MiB, active tasks: 32\n' +
>       '[DLManager] INFO:  + Download\t- 1.99 MiB/s (raw) / 2.00 MiB/s (decompressed)\n' +
>       '[DLManager] INFO:  + Disk\t- 0.00 MiB/s (write) / 0.00 MiB/s (read)\n' +
>       '[DLManager] INFO: = Progress: 16.20% (3918/24179), Running for 00:48:49, ETA: 04:12:28\n' +
>       '[DLManager] INFO:  - Downloaded: 3744.62 MiB, Written: 3822.30 MiB\n' +
>       '[DLManager] INFO:  - Cache usage: 59.0 MiB, active tasks: 32\n' +
>       '[DLManager] INFO:  + Download\t- 2.98 MiB/s (raw) / 3.00 MiB/s (decompressed)\n' +
>       '[DLManager] INFO:  + Disk\t- 4.99 MiB/s (write) / 0.00 MiB/s (read)\n' +
>       '[DLManager] INFO: = Progress: 16.22% (3921/24179), Running for 00:48:50, ETA: 04:12:19\n' +
>       '[DLManager] INFO:  - Downloaded: 3745.62 MiB, Written: 3825.30 MiB\n' +
>       '[DLManager] INFO:  - Cac',
>     stderr: ''
>   }
> }
> finished installing
> Progress: Silene 16.22%/3745.62
> MiB/04:12:19
> 
> ```

What file system is that? EXT4? Can you try with a few others? Like FAT32 and BTRFS.

The issue, I'm guessing is Heroic failing to read stdout properly. This "should" be fixed using a socket implementation instead of constantly polling the file.

**Comment by flavioislima** [comment]
> > ```
> > System:
> >   Host: optipc Kernel: 5.13.0-rc2 x86_64 bits: 64 Desktop: Xfce 4.16.0 
> >   Distro: Debian GNU/Linux 11 (bullseye) 
> > Machine:
> >   Type: Desktop Mobo: ASUSTeK model: PRIME B450M-K v: Rev X.0x 
> >   serial: <superuser required> UEFI: American Megatrends v: 3002 
> >   date: 03/11/2021 
> > CPU:
> >   Info: 6-Core AMD Ryzen 5 2600 [MT MCP] speed: 1371 MHz 
> >   min/max: 1550/3400 MHz 
> > Graphics:
> >   Device-1: AMD Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] 
> >   driver: amdgpu v: kernel 
> >   Device-2: GEMBIRD Generic UVC 1.00 camera [AppoTech AX2311] type: USB 
> >   driver: uvcvideo 
> >   Display: x11 server: X.Org 1.20.11 driver: loaded: amdgpu 
> >   resolution: 3840x2160~60Hz 
> >   OpenGL: renderer: Radeon RX 580 Series (POLARIS10 DRM 3.41.0 5.13.0-rc2 
> >   LLVM 12.0.0) 
> >   v: 4.6 Mesa 21.2.0-devel (git-0df249f 2021-05-19 focal-oibaf-ppa) 
> > ```
> > The download failed in 16.22% with the Close to the Sun game that is 20 GB.
> > ```
> >     '[DLManager] INFO:  - Downloaded: 3738.65 MiB, Written: 3817.30 MiB\n' +
> >       '[DLManager] INFO:  - Cache usage: 58.0 MiB, active tasks: 32\n' +
> >       '[DLManager] INFO:  + Download\t- 1.00 MiB/s (raw) / 1.00 MiB/s (decompressed)\n' +
> >       '[DLManager] INFO:  + Disk\t- 7.99 MiB/s (write) / 0.00 MiB/s (read)\n' +
> >       '[DLManager] INFO: = Progress: 16.18% (3913/24179), Running for 00:48:47, ETA: 04:12:40\n' +
> >       '[DLManager] INFO:  - Downloaded: 3739.65 MiB, Written: 3817.30 MiB\n' +
> >       '[DLManager] INFO:  - Cache usage: 59.0 MiB, active tasks: 32\n' +
> >       '[DLManager] INFO:  + Download\t- 1.00 MiB/s (raw) / 1.00 MiB/s (decompressed)\n' +
> >       '[DLManager] INFO:  + Disk\t- 0.00 MiB/s (write) / 0.00 MiB/s (read)\n' +
> >       '[DLManager] INFO: = Progress: 16.18% (3913/24179), Running for 00:48:48, ETA: 04:12:45\n' +
> >       '[DLManager] INFO:  - Downloaded: 3741.64 MiB, Written: 3817.30 MiB\n' +
> >       '[DLManager] INFO:  - Cache usage: 61.0 MiB, active tasks: 32\n' +
> >       '[DLManager] INFO:  + Download\t- 1.99 MiB/s (raw) / 2.00 MiB/s (decompressed)\n' +
> >       '[DLManager] INFO:  + Disk\t- 0.00 MiB/s (write) / 0.00 MiB/s (read)\n' +
> >       '[DLManager] INFO: = Progress: 16.20% (3918/24179), Running for 00:48:49, ETA: 04:12:28\n' +
> >       '[DLManager] INFO:  - Downloaded: 3744.62 MiB, Written: 3822.30 MiB\n' +
> >       '[DLManager] INFO:  - Cache usage: 59.0 MiB, active tasks: 32\n' +
> >       '[DLManager] INFO:  + Download\t- 2.98 MiB/s (raw) / 3.00 MiB/s (decompressed)\n' +
> >       '[DLManager] INFO:  + Disk\t- 4.99 MiB/s (write) / 0.00 MiB/s (read)\n' +
> >       '[DLManager] INFO: = Progress: 16.22% (3921/24179), Running for 00:48:50, ETA: 04:12:19\n' +
> >       '[DLManager] INFO:  - Downloaded: 3745.62 MiB, Written: 3825.30 MiB\n' +
> >       '[DLManager] INFO:  - Cac',
> >     stderr: ''
> >   }
> > }
> > finished installing
> > Progress: Silene 16.22%/3745.62
> > MiB/04:12:19
> > 
> > ```
> 
> What file system is that? EXT4? Can you try with a few others? Like FAT32 and BTRFS.
> 
> The issue, I'm guessing is Heroic failing to read stdout properly. This "should" be fixed using a socket implementation instead of constantly polling the file.

So then we should make an implementation for that  right away because I'm out of ideas now and getting tired 😞

**Comment by debiangamer** [comment]
What file system is that? EXT4?

Yes, I use ext4.

**Comment by adityaruplaha** [comment]
> > The issue, I'm guessing is Heroic failing to read stdout properly. This "should" be fixed using a socket implementation instead of constantly polling the file.
> 
> So then we should make an implementation for that  right away because I'm out of ideas now and getting tired 😞

Yeah I'll try to. I don't know how to do this stuff using JS frameworks though. I'm a C++ guy myself. Let me see what I can do.

**Comment by GM-Script-Writer-62850** [comment]
In python this how i handle a file not being in a readable state
```

def readJSON(s):
	try:
		with open("/var/www/html/"+s,'r') as cfg:
			cfg=json.load(cfg)
	except:
		time.sleep(0.005)
		cfg=readJSON(s)
	return cfg
```
i would try something similar in the `getProgress` function assuming that is the fn that reads and/or parses the file's content

**Comment by benthetechguy** [comment]
> @debiangamer @benthetechguy @spider3000 @jarrard @BiRo96 @DuttaAB-dev
> Whats your hardware specs by the way?
> Memory and internet speed.
> Are you guys using the home folder on an HDD or SSD?
> 
> Thanks

i5-4590
GTX 1050 Ti
16 GB RAM
25 Mbps down 5 Mbps up
root on SSD, home on HDD

**Comment by DuttaAB-dev** [comment]
> @debiangamer @benthetechguy @spider3000 @jarrard @BiRo96 @DuttaAB-dev 
> Whats your hardware specs by the way?
> Memory and internet speed. 
> Are you guys using the home folder on an HDD or SSD?
> 
> Thanks

Device - Acer Aspire 5(2019)

Ram - 8(4+2)GB DDR4 2400MHz
CPU - Intel i5 8th gen(8265u)(4c 8t)
GPU - Intel UHD 620/Nvidia MX250(hybrid) 
Storage(home/root) - WD M.2NVME SSD 512GB
Internet speed  ~ 70mbps ups/downs 
OS - Pop!_OS 21.04(beta)

**Comment by DuttaAB-dev** [comment]
> > @debiangamer @benthetechguy @spider3000 @jarrard @BiRo96 @DuttaAB-dev 
> > Whats your hardware specs by the way?
> > Memory and internet speed. 
> > Are you guys using the home folder on an HDD or SSD?
> > 
> > Thanks
> 
> Device - Acer Aspire 5(2019)
> 
> Ram - 8(4+2)GB DDR4 2400MHz
> CPU - Intel i5 8th gen(8265u)(4c 8t)
> GPU - Intel UHD 620/Nvidia MX250(hybrid) 
> Storage(home/root) - WD M.2NVME SSD 512GB
> Internet speed  ~ 70mbps ups/downs 
> OS - Pop!_OS 21.04(beta)
> 

Add optional opt-in telemetry for hardware data?

**Comment by debiangamer** [comment]
The error is: 'stdout maxBuffer length exceeded' in
```
// TODO(adityaruplaha):Create a socket connection for requestGameProgress
    try {
      Library.get().installState(this.appName, true)
      return await execAsync(command, {maxBuffer: 1024*500 ,shell:shell})
    } catch (error) {
      console.log(`Error happened:`, error.message)
      Library.get().installState(this.appName, false)
      return errorHandler(logPath)
    }
```
Increasing the maxBuffer value from default 200KB might help. Testing now with the Close to the Sun game.

**Comment by flavioislima** [comment]
> > > @debiangamer @benthetechguy @spider3000 @jarrard @BiRo96 @DuttaAB-dev 
> > > Whats your hardware specs by the way?
> > > Memory and internet speed. 
> > > Are you guys using the home folder on an HDD or SSD?
> > > 
> > > Thanks
> > 
> > Device - Acer Aspire 5(2019)
> > 
> > Ram - 8(4+2)GB DDR4 2400MHz
> > CPU - Intel i5 8th gen(8265u)(4c 8t)
> > GPU - Intel UHD 620/Nvidia MX250(hybrid) 
> > Storage(home/root) - WD M.2NVME SSD 512GB
> > Internet speed  ~ 70mbps ups/downs 
> > OS - Pop!_OS 21.04(beta)
> > 
> 
> Add optional opt-in telemetry for hardware data? 

Man, after what happened with Audacity when they decided to put some telemetry on it, that makes TOTAL sense for Open Source apps since we need info, other wise we will never have good free software compared to the proprietary ones that Have telemetry by default. I don't know, unless we want to kill heroic, I won't be adding telemetry soon.
The Linux community need an upgrade on their minds first 😅

**Comment by flavioislima** [comment]
> The error is: 'stdout maxBuffer length exceeded' in
> ```
> // TODO(adityaruplaha):Create a socket connection for requestGameProgress
>     try {
>       Library.get().installState(this.appName, true)
>       return await execAsync(command, {maxBuffer: 1024*500 ,shell:shell})
>     } catch (error) {
>       console.log(`Error happened:`, error.message)
>       Library.get().installState(this.appName, false)
>       return errorHandler(logPath)
>     }
> ```
> Increasing the maxBuffer value from default 200KB might help. Testing now with the Close to the Sun game and it did not help.
> 
> 

That makes a lot of sense. Maybe, on fast connections we don't have this issue since we have less logs. But you said you tried and it didn't work?

**Comment by debiangamer** [comment]
See my updated comment

**Comment by DuttaAB-dev** [comment]
> > > > @debiangamer @benthetechguy @spider3000 @jarrard @BiRo96 @DuttaAB-dev
> > > > Whats your hardware specs by the way?
> > > > Memory and internet speed.
> > > > Are you guys using the home folder on an HDD or SSD?
> > > > Thanks
> > > 
> > > 
> > > Device - Acer Aspire 5(2019)
> > > Ram - 8(4+2)GB DDR4 2400MHz
> > > CPU - Intel i5 8th gen(8265u)(4c 8t)
> > > GPU - Intel UHD 620/Nvidia MX250(hybrid)
> > > Storage(home/root) - WD M.2NVME SSD 512GB
> > > Internet speed  ~ 70mbps ups/downs
> > > OS - Pop!_OS 21.04(beta)
> > 
> > 
> > Add optional opt-in telemetry for hardware data?
> 
> Man, after what happened with Audacity when they decided to put some telemetry on it, that makes TOTAL sense for Open Source apps since we need info, other wise we will never have good free software compared to the proprietary ones that Have telemetry by default. I don't know, unless we want to kill heroic, I won't be adding telemetry soon.
> The Linux community need an upgrade on their minds first

Well the change in mindsets will come along but first the devs will have to make a change to their approach and slightly move away from the bad aspects of linux stereotypes and sooner or later the users will follow suite. Audacity's main gripe was that it used google analytics to serve its purpose. Maybe I dont know much as I'm still just in high school and just recently started to get my feet wet with linux and coding. Yet, I think that it might be the right thing to do. Sometimes to beat greater the foe, you might need to master some of their practices(the foe here being proprietary software). 
Just a little thought of mine. Sorry for cluttering up everyone's inboxes😓

**Comment by flavioislima** [comment]
> See my updated comment
> 

I can't see what's new 😳
For me it says only that you're trying with close to the sun. But before it said it didn't worked so I'm confused 🤔

**Comment by debiangamer** [comment]
Here is my patched version Debian package with maxBuffer: 2 * 1024 * 1024. You can try it out with large games.
https://www.mediafire.com/file/58pfkbsj03iaypr/heroic_1.7.0_amd64.deb/file

**Comment by adityaruplaha** [comment]
> > Add optional opt-in telemetry for hardware data? 
> 
> Man, after what happened with Audacity when they decided to put some telemetry on it, that makes TOTAL sense for Open Source apps since we need info, other wise we will never have good free software compared to the proprietary ones that Have telemetry by default. I don't know, unless we want to kill heroic, I won't be adding telemetry soon.
> The Linux community need an upgrade on their minds first 😅

+ We have nowhere to host it anyways.

**Comment by debiangamer** [comment]
> > See my updated comment
> 
> I can't see what's new flushed
> For me it says only that you're trying with close to the sun. But before it said it didn't worked so I'm confused thinking

500 KB is under the  default value 1025 KB and download stopped in 3%. I am testing currently with the 20 GB game, 13% downloaded now.

**Comment by adityaruplaha** [comment]
> Well the change in mindsets will come along but first the devs will have to make a change to their approach and slightly move away from the bad aspects of linux stereotypes and sooner or later the users will follow suite. Audacity's main gripe was that it used google analytics to serve its purpose. Maybe I dont know much as I'm still just in high school and just recently started to get my feet wet with linux and coding. Yet, I think that it might be the right thing to do. Sometimes to beat greater the foe, you might need to master some of their practices(the foe here being proprietary software). 
> Just a little thought of mine. Sorry for cluttering up everyone's inboxes😓

That's a good attitude, but we'd much rather just log it for now (logging is WIP) and use that for diagnosis.

The problem really isn't lack of data. The problem is that Heroic doesn't have a huge number of active developers, so often critical issues go unnoticed, and even if they are noticed, no one is around to put the time into fixing it. 

Here's currently everything we (the core team) are working on:
1. DevOps changes.
2. A major backend refactor.
3. Logging.
4. Implementing a protocol for communicating with Heroic.
5. GOG Integration.
6. OS compatibility.
7. Fixing critical bugs, UI issues.
8. Keeping documentation accurate and up-to-date.

Also, we don't have any tests whatsoever (we've been trying), so you get an idea. Honestly, when the entire team is at peak productivity, we get a lot of stuff done really fast (see the 1.5.8 patch notes) but when we aren't, we really can't support all that code actively.

Anyways, sorry about the rant. This issue has been getting on my nerves.

**Comment by flavioislima** [comment]
> > > See my updated comment
> > 
> > I can't see what's new flushed
> > For me it says only that you're trying with close to the sun. But before it said it didn't worked so I'm confused thinking
> 
> 500 KB is under the  default value 1025 KB and download stopped in 3%. I am testing currently with the 20 GB game, 13% downloaded now.

Nice. Looks promising then 😁

**Comment by debiangamer** [comment]
I did manage to download a 20 GB game with maxBuffer: 6\*1024\*1024.
```
try {
      Library.get().installState(this.appName, true)
      return await execAsync(command, {maxBuffer: 6*1024*1024 ,shell:shell})
    } catch (error) {
        console.log(`Error happened:`, error.message);
        Library.get().installState(this.appName, false);
        return errorHandler(logPath)
      }
``` 
Here is the Debian package to test with large games: https://www.mediafire.com/file/brge260oq3cstup/heroic_1.7.0_amd64.deb/file

**Comment by flavioislima** [comment]
> I did manage to download a 20 GB game with maxBuffer: 6*1024*1024.
> 
> ```
> try {
>       Library.get().installState(this.appName, true)
>       return await execAsync(command, {maxBuffer: 6*1024*1024 ,shell:shell})
>     } catch (error) {
>         console.log(`Error happened:`, error.message);
>         Library.get().installState(this.appName, false);
>         return errorHandler(logPath)
>       }
> ```
> 
> Here is the Debian package to test with large games: https://www.mediafire.com/file/brge260oq3cstup/heroic_1.7.0_amd64.deb/file

Man, that's amazing. It looks like you solved the oldest and one of the most difficult bugs in Heroic.
I'll release a new version this week with the fix.
I just think I'll set it to be 10 or more instead of 6 since I think it can still break to download games like GTAV on really slow connections. I just need to do some research to check if this will have some performance impact like increase the memory consumption.
Another idea is to have this as a debug option under settings, where the user can manually setup some value in case the installation breaks.

But thanks a lof for helping with this.

**Comment by adityaruplaha** [comment]
> Another idea is to have this as a debug option under settings, where the user can manually setup some value in case the installation breaks.

Don't bother, working on a socket based implementation that should circumvent this entirely.

Also @debiangamer, one could say this actions were _heroic_. :kekw:

**Comment by debiangamer** [comment]
> > Another idea is to have this as a debug option under settings, where the user can manually setup some value in case the installation breaks.
> 
> Don't bother, working on a socket based implementation that should circumvent this entirely.

Your patches still call:
return await execAsync(command, execOptions)
and that is the root of the error.

**Comment by adityaruplaha** [comment]
Yes but execOptions have been corrected anyways. The max buffer size has been increased. This is still kept since for Windows using bash magic is impossible. So we're gonna do a few tricks to pass data into the TCP server, even on Windows.

**Comment by flavioislima** [comment]
> Yes but execOptions have been corrected anyways. The max buffer size has been increased. This is still kept since for Windows using bash magic is impossible. So we're gonna do a few tricks to pass data into the TCP server, even on Windows.

like @debiangamer said, this new implementation won't fix the bug because that's is not what's is causing it.
What is causing it is that we are using `exec` to call legendary and, even though we don't use stdout for anything, the command has a `maxBuffer` that what was causing the error.
A definitive solution would be to change it to use `spawn` that reads the data along with the command. But I tried it, it was my first option when I started Heroic, and I could not get it working.
I know we can call it and read the data from the child. 

You can find more info on the nodejs page about child processes

**Comment by adityaruplaha** [comment]
> > Yes but execOptions have been corrected anyways. The max buffer size has been increased. This is still kept since for Windows using bash magic is impossible. So we're gonna do a few tricks to pass data into the TCP server, even on Windows.
> 
> like @debiangamer said, this new implementation won't fix the bug because that's is not what's is causing it.
> What is causing it is that we are using `exec` to call legendary and, even though we don't use stdout for anything, the command has a `maxBuffer` that what was causing the error.
> A definitive solution would be to change it to use `spawn` that reads the data along with the command. But I tried it, it was my first option when I started Heroic, and I could not get it working.
> I know we can call it and read the data from the child.
> 
> You can find more info on the nodejs page about child processes

It will since stdout is empty. Look closely, stdout gets fed into the TCP server. There's no stdout for the overall command.

**Comment by flavioislima** [comment]
> > > Yes but execOptions have been corrected anyways. The max buffer size has been increased. This is still kept since for Windows using bash magic is impossible. So we're gonna do a few tricks to pass data into the TCP server, even on Windows.
> > 
> > 
> > like @debiangamer said, this new implementation won't fix the bug because that's is not what's is causing it.
> > What is causing it is that we are using `exec` to call legendary and, even though we don't use stdout for anything, the command has a `maxBuffer` that what was causing the error.
> > A definitive solution would be to change it to use `spawn` that reads the data along with the command. But I tried it, it was my first option when I started Heroic, and I could not get it working.
> > I know we can call it and read the data from the child.
> > You can find more info on the nodejs page about child processes
> 
> It will since stdout is empty. Look closely, stdout gets fed into the TCP server. There's no stdout for the overall command. In fact the changes can even be reverted safely now.

Thats not what I mean.
exec will always have an stdout and stderr. The command will always have a result no matter where you put it.
so it will still crash in case we don't pass the maxBuffer to it. You can try it by yourself.
With your current implementation, change the maxBuffer to a really small number like 100 and try downloading any game, it will crash in a few seconds.

**Comment by adityaruplaha** [comment]
Alright I'll test this, but I'm quite confident that maxBuffer won't be an issue, as stdout and stderr are guaranteed to be empty.
