### ISSUE TITLE
Games not downloading or launching.

### ISSUE THREAD

**Issue by AireagoirSteam** [Heroic-Games-Launcher/HeroicGamesLauncher#2196]
### Describe the bug

Ever since the 2.5.1 version my games will not download and any games installed won't launch even though they do launch on version 2.5.0.

Go to launch an installed game hit play and game does not launch and heroic just says play again.

Go to install a game and game says fetching download size constantly.
[log.txt](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/files/10229858/log.txt)

### Add logs

```text
(16:43:40) INFO:    [Connection]:       Connectivity: check-online
(16:43:40) INFO:    [Connection]:       Pinging external endpoints
(16:43:40) INFO:    [Legendary]:        Running command: /tmp/.mount_Heroic1DjYiG/resources/app.asar.unpacked/build/bin/linux/legendary --version
(16:43:40) INFO:    [Legendary]:        Legendary location: /tmp/.mount_Heroic1DjYiG/resources/app.asar.unpacked/build/bin/linux/legendary
(16:43:40) INFO:    [Gog]:              GOGDL location: /tmp/.mount_Heroic1DjYiG/resources/app.asar.unpacked/build/bin/linux/gogdl
(16:43:41) WARNING: [Backend]:          Failed to register protocol with OS.
(16:43:41) INFO:    [Gog]:              Running command: /tmp/.mount_Heroic1DjYiG/resources/app.asar.unpacked/build/bin/linux/gogdl --version
(16:43:41) INFO:    [Connection]:       Connectivity: online
(16:43:41) INFO:    [Gog]:              Getting data about the user
(16:43:41) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(16:43:41) INFO:    [Gog]:              Saved user data to config
(16:43:41) INFO:    [Backend]:          

Heroic Version: 2.5.2 Yamato
Legendary Version:  0.20.31 Dark Energy (hotfix #5)
GOGdl Version: 
OS: Ubuntu KERNEL: 5.15.0-56-lowlatency ARCH: x64
CPU: Intel Core™ i5-2500K @3.3 GOVERNOR: performance
RAM: Total: 15.57 GiB Available: 13.92 GiB
GRAPHICS: GPU0: NVIDIA GeForce GTX 1050 Ti VRAM: 4096MB DRIVER: 525.60.11 
PROTOCOL: x11

(16:43:42) INFO:    [Backend]:          Checking for new Heroic Updates
(16:43:42) INFO:    [Backend]:          Checking for current version changelog
(16:43:42) INFO:    [Frontend]:         Refreshing Library
(16:43:42) INFO:    [Legendary]:        Refreshing library...
(16:43:42) INFO:    [Legendary]:        Refreshing Epic Games...
(16:43:42) INFO:    [Legendary]:        Game list updated, got 217 games & DLCs
(16:43:42) INFO:    [Gog]:              Getting GOG library
(16:43:42) INFO:    [Backend]:          Frontend Ready
(16:43:42) INFO:    [Legendary]:        Running command: /tmp/.mount_Heroic1DjYiG/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(16:43:43) INFO:    [Gog]:              Number of library pages: 1
(16:43:44) INFO:    [Winetricks]:       Downloading Winetricks
(16:43:44) INFO:    [Gog]:              Saved games data
(16:43:45) WARNING: [Winetricks]:       Error Downloading Winetricks Error: timeout of 1000ms exceeded
    at createError (/tmp/.mount_Heroic1DjYiG/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)
    at RedirectableRequest.handleRequestTimeout (/tmp/.mount_Heroic1DjYiG/resources/app.asar/node_modules/axios/lib/adapters/http.js:369:16)
    at RedirectableRequest.emit (node:events:527:28)
    at Timeout.<anonymous> (/tmp/.mount_Heroic1DjYiG/resources/app.asar/node_modules/follow-redirects/index.js:169:12)
    at listOnTimeout (node:internal/timers:559:17)
    at process.processTimers (node:internal/timers:502:7)
(16:43:47) INFO:    [Backend]:          Starting the Download Queue
(16:43:49) INFO:    [Legendary]:        Checking if EOS Overlay is enabled: /tmp/.mount_Heroic1DjYiG/resources/app.asar.unpacked/build/bin/linux/legendary eos-overlay info --prefix /home/aireagoirdsteam/Games/Heroic/Prefixes/RedoutEnhancedEdition
(16:43:49) INFO:    [Backend]:          Using cached HowLongToBeat data for Redout Enhanced Edition 
(16:43:49) DEBUG:   [Legendary]:        Using cached install info
(16:43:49) DEBUG:   [Legendary]:        Using cached install info
(16:43:49) INFO:    [Legendary]:        Abort command "/tmp/.mount_Heroic1DjYiG/resources/app.asar.unpacked/build/bin/linux/legendary eos-overlay info --prefix /home/aireagoirdsteam/Games/Heroic/Prefixes/RedoutEnhancedEdition"
(16:43:56) INFO:    [Backend]:          Getting HowLongToBeat data for Frostpunk
(16:43:56) INFO:    [Gog]:              Getting game metadata: /tmp/.mount_Heroic1DjYiG/resources/app.asar.unpacked/build/bin/linux/gogdl info 1648559910 --token <redacted> --lang=en-US --os windows
(16:43:56) WARNING: [Gog]:              Failed to get Install Info for 1648559910 using linux as platform, returning empty object
(16:43:57) INFO:    [Gog]:              Getting game metadata: /tmp/.mount_Heroic1DjYiG/resources/app.asar.unpacked/build/bin/linux/gogdl info 1648559910 --token <redacted> --lang=en-US --os windows
(16:43:57) WARNING: [Gog]:              Failed to get Install Info for 1648559910 using linux as platform, returning empty object
(16:43:59) INFO:    [Backend]:          Launching Frostpunk (1648559910)
(16:43:59) INFO:    [Backend]:          Preventing display from sleep
(16:43:59) INFO:    [Gog]:              Getting game metadata: /tmp/.mount_Heroic1DjYiG/resources/app.asar.unpacked/build/bin/linux/gogdl info 1648559910 --token <redacted> --lang=en-US --os windows
(16:43:59) WARNING: [Gog]:              Failed to get Install Info for 1648559910 using linux as platform, returning empty object
(16:43:59) INFO:    [Gog]:              Getting game metadata: /tmp/.mount_Heroic1DjYiG/resources/app.asar.unpacked/build/bin/linux/gogdl info 1648559910 --token <redacted> --lang=en-US --os windows
(16:43:59) WARNING: [Gog]:              Failed to get Install Info for 1648559910 using linux as platform, returning empty object
(16:44:00) ERROR:   [Backend]:          Couldn't find all library folders of Wine Default - wine-7.10!
Missing undefined and/or undefined!
Falling back to system libraries!
(16:44:00) DEBUG:   [Backend]:          Running Wine command: wineboot --init
(16:44:08) INFO:    [DXVKInstaller]:    installing dxvk on... /mnt/C4E8DA29E8DA1A0E/heroic/Frostpunk-prfx
(16:44:08) INFO:    [DXVKInstaller]:    dxvk already installed!
(16:44:08) INFO:    [DXVKInstaller]:    installing vkd3d on... /mnt/C4E8DA29E8DA1A0E/heroic/Frostpunk-prfx
(16:44:08) INFO:    [DXVKInstaller]:    vkd3d already installed!
(16:44:08) ERROR:   [Backend]:          Couldn't find all library folders of Wine Default - wine-7.10!
Missing undefined and/or undefined!
Falling back to system libraries!
(16:44:08) INFO:    [Gog]:              Launching Frostpunk: DRI_PRIME=1 __NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia __GL_SHADER_DISK_CACHE_PATH=/mnt/C4E8DA29E8DA1A0E/heroic/Frostpunk-prfx/ __GL_SHADER_DISK_CACHE_SKIP_CLEANUP=1 LD_PRELOAD= WINEPREFIX=/mnt/C4E8DA29E8DA1A0E/heroic/Frostpunk-prfx WINEESYNC=1 ORIG_LD_LIBRARY_PATH=/tmp/.mount_Heroic1DjYiG/usr/lib: /usr/bin/gamemoderun /tmp/.mount_Heroic1DjYiG/resources/app.asar.unpacked/build/bin/linux/gogdl launch /mnt/C4E8DA29E8DA1A0E/heroic/Frostpunk 1648559910 --wine /usr/bin/wine --platform windows
(16:44:08) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(16:44:08) INFO:    [Frontend]:         Refreshing Library
(16:44:08) INFO:    [Gog]:              Getting GOG library
(16:44:08) INFO:    [Gog]:              Getting game metadata: /tmp/.mount_Heroic1DjYiG/resources/app.asar.unpacked/build/bin/linux/gogdl info 1648559910 --token <redacted> --lang=en-US --os windows
(16:44:08) WARNING: [Gog]:              Failed to get Install Info for 1648559910 using linux as platform, returning empty object
(16:44:08) INFO:    [Gog]:              Getting game metadata: /tmp/.mount_Heroic1DjYiG/resources/app.asar.unpacked/build/bin/linux/gogdl info 1648559910 --token <redacted> --lang=en-US --os windows
(16:44:08) WARNING: [Gog]:              Failed to get Install Info for 1648559910 using linux as platform, returning empty object
(16:44:09) INFO:    [Gog]:              Number of library pages: 1
(16:44:10) INFO:    [Gog]:              Saved games data
(16:44:10) INFO:    [Gog]:              Getting game metadata: /tmp/.mount_Heroic1DjYiG/resources/app.asar.unpacked/build/bin/linux/gogdl info 1648559910 --token <redacted> --lang=en-US --os windows
(16:44:10) WARNING: [Gog]:              Failed to get Install Info for 1648559910 using linux as platform, returning empty object
(16:44:10) INFO:    [Gog]:              Getting game metadata: /tmp/.mount_Heroic1DjYiG/resources/app.asar.unpacked/build/bin/linux/gogdl info 1648559910 --token <redacted> --lang=en-US --os windows
(16:44:10) WARNING: [Gog]:              Failed to get Install Info for 1648559910 using linux as platform, returning empty object
```

### Steps to reproduce

Open heroic.
Go to library page click play.

Go to library page click install.

### Expected behavior

Being able to play curently installed games or download and install and owned game like I can in version 2.5.0 of heroic.

### System Information

Ubuntu studio 20.04
- Heroic Version 2.5.2 hotfix

**Comment by AireagoirSteam** [comment]
> Maybe try logging out and on again. Actually, log on the epic website first, it seems it is requiring that some users put their date of birth there.
> 
> OR this is also happening with GOG games?
> 
> @AireagoirSteam have you tried downloading Wine-GE or proton?

I haven't tried downloading wine-ge or proton.

**Comment by AireagoirSteam** [comment]
Just tried downloading and nothing happened or is shown in the download menu.

**Comment by ajhbh** [comment]
I am experiencing this problem too, running Linux Mint 20.3 (based on Ubuntu 20.04) using the deb Heroic package. It is only affecting GOG games. 
```
(01:27:47) INFO:    [Gog]:              Getting game metadata: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl info 1847879387 --token <redacted> --lang=en-US --os windows
(01:27:47) INFO:    [Gog]:              Getting game metadata: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl info 1847879387 --token <redacted> --lang=en-US --os windows
(01:27:47) WARNING: [Gog]:              Failed to get Install Info for 1847879387 using linux as platform, returning empty object
(01:27:47) WARNING: [Gog]:              Failed to get Install Info for 1847879387 using linux as platform, returning empty object
```

I believe the issue is a change to gogdl system requirements as if I run directly the gogdl binary in a terminal `/opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl info 1847879387 --token <redacted> --lang=en-US --os windows` there is an error about GLIBC 2.35 not found. 
```[41383] Error loading Python lib '/tmp/_MEIdPj7Oi/libpython3.9.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /tmp/_MEIdPj7Oi/libpython3.9.so.1.0)```

I believe Ubuntu 20.04 has GLIBC 2.31.

**Comment by ajhbh** [comment]
Also I've now just tried using the gogdl binary from the Heroic 2.5.0 release as a alternative gogdl binary in the Heroic advanced settings in Heroic 2.5.2 and that restores the ability to download and install games successfully again. In case that helps anyone.

**Comment by flavioislima** [comment]
> Also I've now just tried using the gogdl binary from the Heroic 2.5.0 release as a alternative gogdl binary in the Heroic advanced settings in Heroic 2.5.2 and that restores the ability to download and install games successfully again. In case that helps anyone.

Although this works, it will also break downloading some games since the latest release fixed getting dependencies when installing some old games.

We will change the gogdl workflow to build it on a older Ubuntu version and that should fix this issue I believe.

**Comment by ronoaldo** [comment]
I'm facing the same issue, no longer able to download the games. I can confirm the workaround. This one was posted on Discord by Linguin user:

```
https://github.com/Heroic-Games-Launcher/heroic-gogdl/actions/runs/3725507898
download gogdl-Linux extract it,
make it executable, 
set it as alternative gogdl exe in heroic settings
that one uses older github workflow so that should work
```

**Comment by acheronfail** [comment]
FWIW I'm getting this issue on the Steam Deck - can't install GOG games.

Using the `gogdl` binary from @ronoaldo's comment makes it start to work again, though the GOG installs seem very flaky (had to install the same game about 5 times before it completely successfully, it kept hanging midway though a download).

**Comment by arielj** [comment]
is this still an issue with Heroic 2.7? can anyone confirm?

**Comment by MarwanKhalife** [comment]
@arielj Still facing this issue indeed.
It starts the download however does not show any progress. 
At a point it starts installing (indicated int he UI) after which it just reverts back to showing the Install button.

Only facing this with GOG games. Epic games install just fine.

I've not tried the workaround though. Also not going to try it. Just leaving it for now and see if I can find an alternative method of installing GOG games.

**Comment by arielj** [comment]
can anyone confirm if this is still an issue in Heroic 2.11.0?

**Comment by arielj** [comment]
closing, no comments since jan 2024
