### ISSUE TITLE
Heroic (flatpak) does not start anymore

### ISSUE THREAD

**Issue by gabrielepigozzo** [Heroic-Games-Launcher/HeroicGamesLauncher#2520]
### Describe the bug

flatpak commit: e3e71a2aec0260927a39953551d0fd822d5bc419256efd5fc78345a84b89cecb
heroci does not start with error:
"bwrap: Can't bind mount /oldroot/home/gab/.steam on /newroot/home/gab/.steam: Unable to mount source on destination: No such file or directory"

### Add logs

```text
since heroic doesn't start I cannot provide logs
```

### Steps to reproduce

1. run:  flatpak run com.heroicgameslauncher.hgl

### Expected behavior

heroic interface shows up

### Heroic Version

Latest Stable

### System Information

- xubuntu 22.10

**Comment by Nocccer** [comment]
Did you reinstall with 
`flatpak  install com.heroicgameslauncher.hgl --reinstall`?

Does the error still exist after?

**Comment by gabrielepigozzo** [comment]
Hi Niklas,
same error:

$ flatpak install com.heroicgameslauncher.hgl --reinstall
Looking for matches…


        ID                                    Branch           Op
 Remote           Download
 1. [✓] com.heroicgameslauncher.hgl           stable           i
flathub          1,0 kB / 155,5 MB

Installation complete.
$ flatpak run com.heroicgameslauncher.hgl
bwrap: Can't bind mount /oldroot/home/gab/.steam on
/newroot/home/gab/.steam: Unable to mount source on destination: No such
file or directory

Regards
--
Gabriele Pigozzo

**Comment by gabrielepigozzo** [comment]
Hi Flavio,
I rolled back to previous commit
(9db0e4daaadbba3bdb6d271bd53b45228139b2eaa140a85dc971cd23885f44f8) and
everything is working again.
I already have flatseal installed and heroic has home permissions.
Yes, I have Steam installed.
Yes. I have the folder ~/.steam and heroic can access it.

Regards.
--
Gabriele Pigozzo

**Comment by gabrielepigozzo** [comment]
No idea, those dirs don't exist on my system:

***@***.***:~# find / -type d -name newroot
***@***.***:~# find / -type d -name oldroot

Regards.
--
Gabriele Pigozzo

**Comment by imLinguin** [comment]
Try repairing the flatpak install `$ flatpak repair`, you may need a root privileges depending on scope where heroic is installed

**Comment by gabrielepigozzo** [comment]
Same result as before:

***@***.***:~$ flatpak repair
Working on the system installation at /var/lib/flatpak
[68/69] Verifying flathub:app/com.github.alexhuntley.Plots/x86_64/stable…
Checking remotes...
***@***.***:~$ echo $?
0
***@***.***:~$ flatpak run com.heroicgameslauncher.hgl
bwrap: Can't bind mount /oldroot/home/gab/.steam on
/newroot/home/gab/.steam: Unable to mount source on destination: No such
file or directory


Regards.
--
Gabriele Pigozzo

**Comment by sluedecke** [comment]
Same here, heroic stopped working after an update. Downgrading with:


```
sudo flatpak update --commit=9db0e4daaadbba3bdb6d271bd53b45228139b2eaa140a85dc971cd23885f44f8 com.heroicgameslauncher.hgl
```


Makes it work again.

This is what I found in journalctl:

```
Mar 07 01:36:27 steamdeck systemd[1087]: Started Heroic Games Launcher.
 Mar 07 01:36:27 steamdeck systemd[1087]: Started app-flatpak-com.heroicgameslauncher.hgl-3594.scope.
Mar 07 01:36:27 steamdeck plasmashell[3605]: bwrap: Can't make symlink at /home/deck/Games: File exists
```

Games is a symlink to the SD card.

**Comment by motolav** [comment]
I have the same issue when I start the flatpak in console i get the error ```bwrap: Can't make symlink at /home/user/Games: File exists```.
My system has a drive mounted to /mnt/games with a symlink to my home dir titled Games and when I delete that symlink the flatpak creates a folder Games/Heroic in my home dir and complains ```bwrap: Can't mkdir /home/user/Games/Heroic: No such file or directory```

**Comment by NoaLRX** [comment]
> I have the same issue when I start the flatpak in console i get the error `bwrap: Can't make symlink at /home/user/Games: File exists`. My system has a drive mounted to /mnt/games with a symlink to my home dir titled Games and when I delete that symlink the flatpak creates a folder Games/Heroic in my home dir and complains `bwrap: Can't mkdir /home/user/Games/Heroic: No such file or directory`

Thank you for that ! It works now

**Comment by MyCookie** [comment]
I am running into this issue as well. At first I thought it was a symlink bug, as folk have pointed out on SteamOS, and my Steam install is symlinked to another drive. However, moving it back to ``$HOME/.local/share/Steam`` did not solve the problem, as the bug now presents itself as @gabrielepigozzo reported.

> Can you install Flatseal and check if giving heroic permission to home fixes the issue?

This solves the issue, but it is not a viable fix for me, as I don't want to give Heroic blanket permissions to ``$HOME``.

OS: Arch
DE: KDE 5.27

**Comment by motolav** [comment]
In my case changing the default locations in Heroic(using the previous flatpak build) and not using a symlink titled Games in my home directory fixes it. When I recreate the symlink Heroic won't start again even though i have the ~/Games/Heroic - Create permission disabled. 
This is likely a flatpak issue not a Heroic one as others have had similar issues https://github.com/flatpak/flatpak/issues/4894

**Comment by msdobrescu** [comment]
I get this too and I would not change my setup.

`"heroic games" bwrap: Can't make symlink at /home/<myuser>/Games: File exists`

**Comment by gabrielepigozzo** [comment]
Seems to be fixed in the last update (b7307b4504811f485879be22b5e5f83fa62dfbe82352306f014bb6071f6e42aa) at least for me.
Thank you!

**Comment by imLinguin** [comment]
Yes, we rolled back the `--persist` parameter for now. It should be fixed now

**Comment by arielj** [comment]
Closing since the change that causes the issue was reverted and it's working now

**Comment by gabrielepigozzo** [comment]
since commit 9ad64c8d1d770705f6e2aece072ae3e54f3221b86efbc93e848931fa817f2263 this bug si present again.

xubuntu 23.04
X.org / i3wm

$ flatpak -v run com.heroicgameslauncher.hgl
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/gab/.local/share/flatpak
F: Opening user flatpak installation at path /home/gab/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Skipping parental controls check for app/com.heroicgameslauncher.hgl/x86_64/stable since parental controls are disabled globally
F: Opening user flatpak installation at path /home/gab/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/22.08/74b5ae6a53e3f39258f90c664a63ef256097bd77c4229fc11e96bc2dbd2ce0cf/files/lib32 does not exist
F: Cleaning up unused container id 4286259902
F: Cleaning up per-app-ID state for com.heroicgameslauncher.hgl
F: Allocated instance id 372630060
F: Add defaults in dir /com/heroicgameslauncher/hgl/
F: Add locks in dir /com/heroicgameslauncher/hgl/
F: Not sharing "/home/gab/.var/app/com.valvesoftware.Steam" with sandbox: Unable to open path "/home/gab/.var/app/com.valvesoftware.Steam": No such file or directory
F: Not sharing "/run/media" with sandbox: Unable to open path "/run/media": No such file or directory
F: Allowing wayland access
F: Allowing x11 access
F: Allowing pulseaudio access
F: Pulseaudio user configuration file '/home/gab/.config/pulse/client.conf': Error opening file /home/gab/.config/pulse/client.conf: No such file or directory
F: Running 'bwrap --args 42 xdg-dbus-proxy --args=44'
F: Running 'bwrap --args 42 heroic-run'
**bwrap: Can't bind mount /oldroot/home/gab/.steam on /newroot/home/gab/.steam: Unable to mount source on destination: No such file or directory**

Rolling back to commit cc4dbe0daa78d70ab59a14ece03ec6e844988cb57e9260126eede2749a73fe37 fixes the issue.

**Comment by msdobrescu** [comment]
Still broken.
Renamed the Games dir, it creates ~/Games/Heroic and then crashes due to an error complaining ~/Games/Heroic is not a file or directory. It is broken for a long time now, isn't there any clue on how to fix or bypass this?

**Comment by Magyar57** [comment]
I'm having the same issue here... Is there any way to roll back to an earlier version of Heroic before it gets patched again (maybe) ?

**Comment by gabrielepigozzo** [comment]
yes, you can revert to a working version with:
sudo flatpak update  --commit=cc4dbe0daa78d70ab59a14ece03ec6e844988cb57e9260126eede2749a73fe37 com.heroicgameslauncher.hgl

**Comment by arielj** [comment]
Can you try with the latest 2.10.0 release?

**Comment by gabrielepigozzo** [comment]
Hi Ariel,
the issue is still present:
Heroic Games Launcher          com.heroicgameslauncher.hgl
 v2.10.0             stable         system

$ flatpak -v run com.heroicgameslauncher.hgl
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/gab/.local/share/flatpak
F: Opening user flatpak installation at path /home/gab/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Skipping parental controls check for
app/com.heroicgameslauncher.hgl/x86_64/stable since parental controls are
disabled globally
F: Opening user flatpak installation at path /home/gab/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F:
/var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/23.08/75d6f5f7daf46127a5e53608274216b46405b7197894970021bb7230113a30a7/files/lib32
does not exist
F: Cleaning up unused container id 1558645150
F: Cleaning up per-app-ID state for com.heroicgameslauncher.hgl
F: Allocated instance id 2411252079
F: Add defaults in dir /com/heroicgameslauncher/hgl/
F: Add locks in dir /com/heroicgameslauncher/hgl/
F: Not sharing "/home/gab/.var/app/com.valvesoftware.Steam" with sandbox:
Unable to open path "/home/gab/.var/app/com.valvesoftware.Steam": No such
file or directory
F: Not sharing "/run/media" with sandbox: Unable to open path "/run/media":
No such file or directory
F: Allowing wayland access
F: Allowing x11 access
F: Allowing pulseaudio access
F: Pulseaudio user configuration file
'/home/gab/.config/pulse/client.conf': Error opening file
/home/gab/.config/pulse/client.conf: No such file or directory
F: Running 'bwrap --args 42 xdg-dbus-proxy --args=44'
F: Running 'bwrap --args 42 heroic-run'
*bwrap: Can't bind mount /oldroot/home/gab/.steam on
/newroot/home/gab/.steam: Unable to mount source on destination: No such
file or directory*

Regards.
--
Gabriele Pigozzo

**Comment by msdobrescu** [comment]
Hi, I confirm, it persists.

**Comment by DarkVirtue** [comment]
I've just installed Heroic via Flatpak. This is my first Heroic install of any kind. I'm having the same issue as others in this thread:
The launcher runs fine the first time it's launched. On subsequent launches, it crashes:
```
flatpak run com.heroicgameslauncher.hgl 
bwrap: Can't make symlink at /home/vicerious/Games: File exists
```
If I delete the symlink `/home/vicerious/.var/app/com.heroicgameslauncher.hgl/Games`, then Heroic will launch correctly again. It recreates the symlink and will therefore fail to launch the next time.

The symlink it creates points to `../../games`, which would be `/home/vicerious/.var/games`. That path does not exist, so the symlink is broken anyway.

**Comment by gabrielepigozzo** [comment]
hmm, today I removed the flatpak package with:
`flatpak uninstall --delete-data com.heroicgameslauncher.hgl`
adn after reinstallation now ti works correctly
