### ISSUE TITLE
1.5.7 AppImage doesn't list available Wine version in game settings

### ISSUE THREAD

**Issue by dpanter** [Heroic-Games-Launcher/HeroicGamesLauncher#265]
NOTE: The issue was resolved after installing another game.

Several games were installed with 1.5.5 AppImage, the Wine Version list in game settings show all Wine/Proton versions I have installed.
![Screenshot_20210322_170408](https://user-images.githubusercontent.com/14197392/112039829-c4292580-8b44-11eb-9300-fc51fd1ed8b0.png)

With 1.5.6 and 1.5.7 the Wine Version list in game settings is empty, but games still work.
![Screenshot_20210322_170316](https://user-images.githubusercontent.com/14197392/112039925-dc00a980-8b44-11eb-80bf-fa321bbc86a7.png)

All three show the Wine Version list correctly in Global settings.
After installing another game with 1.5.7 this bug fixed itself and all three now list Wine/Proton versions properly for all games.

**Desktop**
- OS: Siduction (Debian sid based), kernel 5.11.7, KDE Plasma 5.20.5
- Games installed with 1.5.5: Cave Story+, World War Z, Eternal Cylinder beta
- Game installed with 1.5.7: A Short Hike

**Comment by robca402** [comment]
I had this exact issue. I can confirm installing another game then restarting heroic launcher populated the list again.

**Comment by flavioislima** [comment]
I think the installation of games is just a coincidence. Probably restarting Heroic or maybe reloading the library (that forces a full reload of the frontend) should fix. But we will take a look on this when we have time.

**Comment by robca402** [comment]
I had restarted heroic a few times before I came here and saw this post. After installing a game it started working.

But with that said it absolutely could have been something else that triggered them showing up again, you would know better than me!

**Comment by dpanter** [comment]
Restarting Heroic did not fix it, as noted I used three versions and restarted each a good number of times. I believe I reloaded the library while poking around but I can't be absolutely certain on that point.

**Comment by adityaruplaha** [comment]
Can you try on latest commit? I think I fixed this issue by accident while refactoring, cuz I definitely didn't have this issue.

**Comment by dpanter** [comment]
Try... what, exactly? The issue is no longer present.

**Comment by adityaruplaha** [comment]
Yeah checking on a fresh install would be a nice idea. If its broken on new installations only, its definitely a bug.

**Comment by dpanter** [comment]
Well the AppImage isn't 'installed' per se. I hope you'll forgive me for not reinstalling Debian... ;)
- deleted config dir `~/.config/heroic/`
- deleted config dir `~/.config/legendary/`
- Heroic AppImage 1.5.5 & 1.5.7
- Legendary AppImage 0.20.6-1 (in the same dir as Heroic)

Started 1.5.5, logged in to EGS with the SID number, no games listed as installed. Set "Default Installation Path" and "WinePrefix folder". Installed Celeste with default options. Wine versions are listed in game settings.

Closed 1.5.5 and started 1.5.7. Wine versions not listed in Celeste game settings.
Refreshed library. Wine versions not listed. Restarted 1.5.7. Wine versions not listed. Refreshed library... and suddenly Wine version are listed in Celeste game settings. Note that I did not start the game at any point. 

Hope this information can help pinpoint the cause.

**Comment by longusnickus** [comment]
i only had proton 5 install in steam, when i downloaded heroic. when i downloaded 6.3, i deleted proton 5
my heroic client still shows proton 5 although, but not 6.3
i added the path to 6.3 manually and it works, but i would appreciate, if the client updates it itself
i also dont know how to delete the proton 5 entry. i does not work anymore... obviously

**Comment by flavioislima** [comment]
> i only had proton 5 install in steam, when i downloaded heroic. when i downloaded 6.3, i deleted proton 5
> my heroic client still shows proton 5, but not 6.3
> i added the path to 6.3 manually and it works, but i would appreciate, if the client updates it itself
> i also dont know how to delete the proton 5 entry. i does not work anymore... obviously

Which paths are you using for proton?

**Comment by flavioislima** [comment]
> Well the AppImage isn't 'installed' per se. I hope you'll forgive me for not reinstalling Debian... ;)
> 
>     * deleted config dir `~/.config/heroic/`
> 
>     * deleted config dir `~/.config/legendary/`
> 
>     * Heroic AppImage 1.5.5 & 1.5.7
> 
>     * Legendary AppImage 0.20.6-1 (in the same dir as Heroic)
> 
> 
> Started 1.5.5, logged in to EGS with the SID number, no games listed as installed. Set "Default Installation Path" and "WinePrefix folder". Installed Celeste with default options. Wine versions are listed in game settings.
> 
> Closed 1.5.5 and started 1.5.7. Wine versions not listed in Celeste game settings.
> Refreshed library. Wine versions not listed. Restarted 1.5.7. Wine versions not listed. Refreshed library... and suddenly Wine version are listed in Celeste game settings. Note that I did not start the game at any point.
> 
> Hope this information can help pinpoint the cause.

Yeah, really weird. This might be fixed on the main branch but we will do more tests before next release.

**Comment by longusnickus** [comment]
> > i only had proton 5 install in steam, when i downloaded heroic. when i downloaded 6.3, i deleted proton 5
> > my heroic client still shows proton 5, but not 6.3
> > i added the path to 6.3 manually and it works, but i would appreciate, if the client updates it itself
> > i also dont know how to delete the proton 5 entry. i does not work anymore... obviously
> 
> Which paths are you using for proton?

its not default. i have an extra SSD for games so its
/run/media/USER/SSD/Steam/steamapps/common/Proton 6.3/
on manjaro

ohhh i see... proton 5 was installed on my home drive. thats weird

**Comment by flavioislima** [comment]
> > > i only had proton 5 install in steam, when i downloaded heroic. when i downloaded 6.3, i deleted proton 5
> > > my heroic client still shows proton 5, but not 6.3
> > > i added the path to 6.3 manually and it works, but i would appreciate, if the client updates it itself
> > > i also dont know how to delete the proton 5 entry. i does not work anymore... obviously
> > 
> > 
> > Which paths are you using for proton?
> 
> its not default. i have an extra SSD for games so its
> /run/media/USER/SSD/Steam/steamapps/common/Proton 6.3/
> on manjaro
> 
> ohhh i see... proton 5 was installed on my home drive. thats weird
> the proton5 folder still exists, even if i deinstalled it. thats explains it

exactly. Right now heroic does not save the proton list anywhere, it reads the directories when you are on the wine settings and then just store the chosen one on the game config and on the default config. But the actual list of Wine/Proton does not exists. So if a folder exists on one of the paths that Heroic searchs for, it will be listed.

**Comment by longusnickus** [comment]
> > > > i only had proton 5 install in steam, when i downloaded heroic. when i downloaded 6.3, i deleted proton 5
> > > > my heroic client still shows proton 5, but not 6.3
> > > > i added the path to 6.3 manually and it works, but i would appreciate, if the client updates it itself
> > > > i also dont know how to delete the proton 5 entry. i does not work anymore... obviously
> > > 
> > > 
> > > Which paths are you using for proton?
> > 
> > 
> > its not default. i have an extra SSD for games so its
> > /run/media/USER/SSD/Steam/steamapps/common/Proton 6.3/
> > on manjaro
> > ohhh i see... proton 5 was installed on my home drive. thats weird
> > the proton5 folder still exists, even if i deinstalled it. thats explains it
> 
> exactly. Right now heroic does not save the proton list anywhere, it reads the directories when you are on the wine settings and then just store the chosen one on the game config and on the default config. But the actual list of Wine/Proton does not exists. So if a folder exists on one of the paths that Heroic searchs for, it will be listed.

my bad. i thought proton5 also was installed on my SSD and its gone because i deleted it
i thought heroic could read my steam library folder paths, but its just the default home path. so i have to make a custom proton path with every major proton update. i can live with that

**Comment by flavioislima** [comment]
Yeah. I have no idea how to get all the paths from Steam. Could not find any file with this info so for now, we only read the ones on the home folder. At least now you can add custom ones 👍🏽

**Comment by dpanter** [comment]
Library paths are stored in config.vdf. I wrote a bash script some time ago to check which compatibility tools were configured to be used with each game in your Steam libraries, perhaps it can help out.
https://gist.github.com/dpanter/4bc3f7dd4983f7f990706acd0214e6af

**Comment by flavioislima** [comment]
> Library paths are stored in config.vdf. I wrote a bash script some time ago to check which compatibility tools were configured to be used with each game in your Steam libraries, perhaps it can help out.
> https://gist.github.com/dpanter/4bc3f7dd4983f7f990706acd0214e6af

It sure will. Thanks for that! 😀

**Comment by adityaruplaha** [comment]
> Right now heroic does not save the proton list anywhere

I think that's a good thing cuz then you need to worry about updating and whatnot. The config system is already pretty complicated post-versioning.

**Comment by adityaruplaha** [comment]
Why is this issue still open?

**Comment by dpanter** [comment]
Closing with the assumption this has been fixed.
