### ISSUE TITLE
Legendary error

### ISSUE THREAD

**Issue by JonnyBro** [Heroic-Games-Launcher/HeroicGamesLauncher#2701]
### Describe the bug

Error shows up when Heroic is opened. I tried fully reinstalling Heroic and EGS.

### Add logs

```text
An error has occurred! Try to Logout and Login on your Epic account.
Available games:
*long games list*
[cli] INFO: Logging in...[Core] INFO: Trying to re-use existing login session...[cli] INFO: Getting game list... (this may take a while)Traceback (most recent call last):
File "legendary\cli.py", line 3069, in <module>
File "legendary\cli.py", line 2980, in main
File "legendary\cli.py", line 272, in list_games
File "encodings\cp1251.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\xf6' in position 24: character maps to <undefined>
[15268] Failed to execute script 'cli' due to unhandled exception!
```

### Steps to reproduce

1. Log into EGS account
2. Open Library
3. Error

### Expected behavior

no error

### Screenshots

![image](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/48434875/e43645ef-7bb2-4a1c-a2c4-43e0f36bb3f7)

### Heroic Version

Latest Stable

### System Information

- OS: Windows

**Comment by JonnyBro** [comment]
looks like [this](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/2700) is the same

**Comment by itz-me-zappex** [comment]
i have similar issue on linux, i should relogin into EGS account every time after reboot/shutdown for avoid this
![2023-05-15_18-26-13](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/85901674/260ac167-7006-4f57-8116-936a33c99c4c)

An error has occurred! Try to Logout and Login on your Epic account.
gamemodeauto:[cli] INFO: Logging in...
Traceback (most recent call last):
File "legendary/cli.py", line 3061, in <module>File "legendary/cli.py", line 2976, in main
File "legendary/cli.py", line 592, in launch_game
File "legendary/core.py", line 187, in login
ValueError: No saved credentials
[5026] Failed to execute script 'cli' due to unhandled exception!

**Comment by LeSnake04** [comment]
Same for me:
```
File "legendary/cli.py", line 3061, in <module>
File "legendary/cli.py", line 2972, in mainFile "legendary/cli.py", line 239, in list_games
UnicodeEncodeError: 'ascii' codec can't encode character '\xae' in position 13: ordinal not in range(128)
[36588] Failed to execute script 'cli' due to unhandled exception!
```

**Comment by deepakgudi-pixel** [comment]
how to switch on MAC?

**Comment by LeSnake04** [comment]
You can select the binary in the global "advanced" settings

The best way is probably brew, but i never touched a mac so i dont know if its available there.

**Comment by Roma15228** [comment]
Please tell us in more detail how to do this, what does it mean to change the binary? I use the Windows version

**Comment by LeSnake04** [comment]
0. Go to library overviews
1. Go to settings:
![Screenshot from 2023-05-27 19-50-35](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/47243761/04224e48-f0fd-490c-bffb-dc377ba2d478)
2. go to advanced
![Screenshot from 2023-05-27 19-50-50](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/47243761/86274fd9-0b12-48b8-ad08-f25be59a6b29)
3. Click on select legendary binary
![Screenshot from 2023-05-27 19-51-15](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/47243761/47bcb49b-1a65-4852-a019-1a4b6d3ea309)

You can get a binary from here: https://github.com/derrod/legendary/releases/.
I suggest removing the custom binary as soon as a fix get released so you dont have to keep  updating legendary.

**Comment by Durus-R** [comment]
I have a similair probleme here, but in my case, it won´t let me download an update.
Logs: ```
An error has occurred! Try to Logout and Login on your Epic account.
Traceback (most recent call last):
File "legendary/cli.py", line 3061, in <module>File "legendary/cli.py", line 3000, in main
File "legendary/cli.py", line 1587, in info
File "legendary/api/egs.py", line 190, in get_user_entitlements
AttributeError: 'NoneType' object has no attribute 'get'
[204] Failed to execute script 'cli' due to unhandled exception!```
and: 
```
(20:07:58) INFO:    [Legendary]:        Refreshing library...

(20:07:58) INFO:    [Legendary]:        Refreshing Epic Games...

(20:07:58) INFO:    [Connection]:       Connectivity: check-online

(20:07:58) INFO:    [Connection]:       Pinging external endpoints

(20:07:58) INFO:    [Legendary]:        Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version

(20:07:59) INFO:    [Legendary]:        Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary

(20:07:59) INFO:    [Gog]:              GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl

(20:07:59) INFO:    [Gog]:              GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl

(20:07:59) INFO:    [Legendary]:        Game list updated, got 248 games & DLCs

(20:07:59) WARNING: [Backend]:          Failed to register protocol with OS.

(20:07:59) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/rene/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json --version

(20:08:00) INFO:    [Connection]:       Connectivity: online

(20:08:00) INFO:    [Gog]:              Checking if login is valid

(20:08:00) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/rene/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth

(20:08:00) INFO:    [Backend]:          

Heroic Version: 2.8.0 Nico Robin

Legendary Version:  0.20.32 Dark Energy (hotfix #6)

GOGdl Version: 0.7.2

Electron Version: 23.1.4

Chrome Version: 110.0.5481.192

NodeJS Version: 18.12.1

OS: Freedesktop SDK KERNEL: 5.15.0-73-generic ARCH: x64

CPU: Intel Core™ i5-3317U @1.7 GOVERNOR: schedutil

RAM: Total: 7.65 GiB Available: 4.75 GiB

GRAPHICS: GPU0: 3rd Gen Core processor Graphics Controller  VRAM: 256MB 

PROTOCOL: x11

(20:08:01) INFO:    [Backend]:          Loading Screen Ready

(20:08:01) INFO:    [Frontend]:         Refreshing undefined Library

(20:08:01) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager

(20:08:01) INFO:    [Gog]:              Found 0 game(s) to update

(20:08:01) INFO:    [Backend]:          Frontend Ready

(20:08:01) INFO:    [Backend]:          Checking for current version changelog

(20:08:01) INFO:    [Legendary]:        Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party

(20:08:02) INFO:    [Winetricks]:       Downloading Winetricks

(20:08:03) WARNING: [Winetricks]:       Error Downloading Winetricks Error: timeout of 1000ms exceeded

    at createError (/app/bin/heroic/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)

    at RedirectableRequest.handleRequestTimeout (/app/bin/heroic/resources/app.asar/node_modules/axios/lib/adapters/http.js:369:16)

    at RedirectableRequest.emit (node:events:513:28)

    at Timeout.<anonymous> (/app/bin/heroic/resources/app.asar/node_modules/follow-redirects/index.js:169:12)

    at listOnTimeout (node:internal/timers:564:17)

    at process.processTimers (node:internal/timers:507:7)

(20:08:04) INFO:    [Legendary]:        Getting more details with 'legendary info'

(20:08:04) INFO:    [Gog]:              Saved username to config file

(20:08:05) INFO:    [Backend]:          Preventing machine to sleep

(20:08:05) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded

(20:08:06) INFO:    [Backend]:          Starting the Download Queue

(20:08:09) INFO:    [Legendary]:        Checking for game updates: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party

(20:08:11) INFO:    [Legendary]:        Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary info 7786b355a13b47a6b3915335117cd0b2 --platform Windows --json

(20:08:40) DEBUG:   [Legendary]:        Update is available for 7786b355a13b47a6b3915335117cd0b2: 37.0.6677 != 37.1.6698

(20:08:40) INFO:    [Legendary]:        Found 1 game to update

(20:08:42) INFO:    [DownloadManager]:  7786b355a13b47a6b3915335117cd0b2 removed from download manager.

(20:08:42) INFO:    [Frontend]:         Refreshing undefined Library

(20:08:42) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager

(20:08:42) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/rene/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth

(20:08:42) INFO:    [Legendary]:        Refreshing library...

(20:08:42) INFO:    [Gog]:              Getting GOG library

(20:08:43) INFO:    [Gog]:              Number of library pages: 1

(20:08:43) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/rene/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth

(20:08:44) INFO:    [Gog]:              Saved games data

(20:08:44) INFO:    [Legendary]:        Getting more details with 'legendary info'

(20:08:45) INFO:    [Backend]:          Preventing machine to sleep

(20:08:45) INFO:    [Frontend]:         Refreshing undefined Library

(20:08:45) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager

(20:08:45) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/rene/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth

(20:08:45) INFO:    [Legendary]:        Refreshing library...

(20:08:45) INFO:    [Gog]:              Getting GOG library

(20:08:46) INFO:    [Gog]:              Number of library pages: 1

(20:08:46) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/rene/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth

(20:08:46) INFO:    [Legendary]:        Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary info 7786b355a13b47a6b3915335117cd0b2 --platform Windows --json

(20:08:47) INFO:    [Gog]:              Saved games data

(20:09:32) INFO:    [Connection]:       Connectivity: offline

(20:09:34) INFO:    [Connection]:       Connectivity: check-online

(20:09:34) INFO:    [Connection]:       Pinging external endpoints

(20:09:34) INFO:    [Connection]:       All ping requests failed:

(20:09:34) INFO:    [Connection]:       AggregateError: All promises were rejected

(20:09:39) INFO:    [Connection]:       Pinging external endpoints

(20:09:41) INFO:    [Connection]:       Connectivity: online

(20:09:47) INFO:    [DownloadManager]:  7786b355a13b47a6b3915335117cd0b2 removed from download manager.

(20:09:47) INFO:    [Frontend]:         Refreshing undefined Library

(20:09:47) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager

(20:09:47) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/rene/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth

(20:09:47) INFO:    [Legendary]:        Refreshing library...

(20:09:47) INFO:    [Backend]:          Stopping Power Saver Blocker

(20:09:47) INFO:    [Gog]:              Getting GOG library

(20:09:48) INFO:    [Legendary]:        Getting more details with 'legendary info'

(20:09:53) INFO:    [Gog]:              Number of library pages: 1

(20:09:53) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/rene/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth

(20:09:55) INFO:    [Legendary]:        Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary info 7786b355a13b47a6b3915335117cd0b2 --platform Windows --json

(20:09:56) INFO:    [Gog]:              Saved games data

(20:10:33) INFO:    [Connection]:       Connectivity: offline

(20:10:33) INFO:    [Connection]:       Connectivity: check-online

(20:10:33) INFO:    [Connection]:       Pinging external endpoints
(20:10:34) INFO:    [Connection]:       Connectivity: online
```

**Comment by LeSnake04** [comment]
@Durus-R I dont think your error is related. This is about the encoding error, your is a None error. I think you should open another issue for this.

**Comment by Durus-R** [comment]
Okay, but it fixed itself after login. Maybe it was also because I hadn't a stable internet connection.

**Comment by JonnyBro** [comment]
Still appears on 2.8.0. Custom binary doesn't fix the issue

**Comment by CrisPell** [comment]
For me worked changing for the custom binary of new compiled legendary: https://github.com/derrod/legendary/releases/tag/0.20.33 (Properties -> permissions -> check "is executable") select it in heroic -> settings -> advanced -> Custom binary.

**Comment by lbr-dev** [comment]
Nothing worked tried installing latest legendary, older version of heroic, alternative login. Nothing worked. This issue is present on all of my devices (amd64 gaming pc with linux mint and also on my arm64 M1 Macbook Air). Waiting for any other suggestion or fix :/

**Comment by 1basti1** [comment]
Im on 0.20.32 and on steam deck. I still get this error popup when I open Heroic or refresh my library.

I don't get logged out and I don't need to login again. It just pops up everytime. It's really annoying.

(I'm on phone right now, so I can't copy/paste the exact log)

but error is \xae in position 13

**Comment by BestSumy** [comment]
> For me worked changing for the custom binary of new compiled legendary: https://github.com/derrod/legendary/releases/tag/0.20.33 (Properties -> permissions -> check "is executable") select it in heroic -> settings -> advanced -> Custom binary.

Thanks man it works!

Guys if you are using win 10 64bit please manually upgrade it to 0.20.33 which fix my problem

**Comment by Arrgonn** [comment]
`sudo pacman -S curl`  & `sudo snap remove heoric` & `flatpak update && flatpak install --reinstall com.heroicgameslauncher.hgl`(https://flathub.org/apps/com.heroicgameslauncher.hgl)

**Comment by JonnyBro** [comment]
Will try a new update, hope it fixes everything (clean install of course)!

**Comment by tuping** [comment]
Heroic Launcher 2.9.2 on Ubuntu Linux:
```
An error has occurred! Try to Logout and Login on your Epic account.
Available games:
...
....
.....
[cli] INFO: Logging in...[Core] INFO: Trying to re-use existing login session...[cli] INFO: Getting game list... (this may take a while)Traceback (most recent call last):
File "legendary/cli.py", line 3061, in <module>
File "legendary/cli.py", line 2972, in main
File "legendary/cli.py", line 239, in list_games
UnicodeEncodeError: 'ascii' codec can't encode character '\xae' in position 18: ordinal not in range(128)
[624] Failed to execute script 'cli' due to unhandled exception!
```

**Comment by 1basti1** [comment]
> Heroic Launcher 2.9.2 on Ubuntu Linux:
> 
> ```
> An error has occurred! Try to Logout and Login on your Epic account.
> Available games:
> ...
> ....
> .....
> [cli] INFO: Logging in...[Core] INFO: Trying to re-use existing login session...[cli] INFO: Getting game list... (this may take a while)Traceback (most recent call last):
> File "legendary/cli.py", line 3061, in <module>
> File "legendary/cli.py", line 2972, in main
> File "legendary/cli.py", line 239, in list_games
> UnicodeEncodeError: 'ascii' codec can't encode character '\xae' in position 18: ordinal not in range(128)
> [624] Failed to execute script 'cli' due to unhandled exception!
> ```

Still same on steam deck. Only solution is to manually use  Legendary 0.20.33. (maybe other versions work too, but that's the one that works and doesn't show this error for me)

**Comment by JM1705** [comment]
I'm having similar issues with the ® symbol in one of my games' titles seemingly not being supported by the unicode codec. It doesn't seem to break anything, but the error message is pretty annoying.

I also can't get rid of the game, as EGS doesn't support deleting games apparently.

**Comment by arielj** [comment]
this should be fixed in 2.10.0, since we updated the legendary binary

**Comment by JonnyBro** [comment]
it's fixed, thank you!

**Comment by BartRoozen** [comment]
> this should be fixed in 2.10.0, since we updated the legendary binary

Still(or again) having the issue on 2.11.0 (legendary 0.20.33) on steam Deck lcd. I haven't used heroic for a good couple months (year?) So maybe that has anything to do with it? I got at least one game to run so that's nice I guess :) thanks for doing the lords work!

**Comment by Wandersport** [comment]
![image](https://github.com/user-attachments/assets/6800abf0-9d3f-40e7-98e7-c3838ef49d47)
Can someone help, its the same error

**Comment by nidal-nijm-games** [comment]
I am in 2025 and this error still persists, I can not install any game from my epic games. Any fix? I am on Steam Deck by the way.
