### ISSUE TITLE
Very slow downloads from Epic Games

### ISSUE THREAD

**Issue by FreezyLemon** [Heroic-Games-Launcher/HeroicGamesLauncher#4096]
### Describe the bug

Similar to #3353. Trying to download games from Epic Games and it only reaches 1-2 MiB/s sporadically instead of my usual speed (>10MiB/s constantly) I get on the Epic Games Store app (on Windows) or other game launchers (e.g. Steam on Linux).

![image](https://github.com/user-attachments/assets/29c4cb2a-c95e-48c7-a05a-b16068d58fad)

It spikes up to ~2MiB but is usually very close to zero. This is not a display bug, I verified the speed with OS tooling and it's trivial to see when I look at the percentage / MB downloaded stat.

The number of download workers is set to "Max".

### Add logs

```text
...

(15:57:50) INFO:    [Legendary]:        Progress for Satisfactory: 47.79%/6174.68MB/01:10:59 Down: 0.68MB/s / Disk: 0MB/s

(15:57:51) INFO:    [Legendary]:        Progress for Satisfactory: 47.8%/6175.56MB/01:10:58 Down: 0.88MB/s / Disk: 2MB/s

(15:57:52) INFO:    [Legendary]:        Progress for Satisfactory: 47.81%/6176.50MB/01:10:59 Down: 0.94MB/s / Disk: 0MB/s

(15:57:53) INFO:    [Legendary]:        Progress for Satisfactory: 47.81%/6177.46MB/01:10:59 Down: 0.95MB/s / Disk: 0MB/s

(15:57:54) INFO:    [Legendary]:        Progress for Satisfactory: 47.82%/6178.41MB/01:11:00 Down: 0.95MB/s / Disk: 0MB/s

(15:57:56) INFO:    [Legendary]:        Progress for Satisfactory: 47.82%/6178.41MB/01:11:00 Down: 0.67MB/s / Disk: 0MB/s

(15:57:57) INFO:    [Legendary]:        Progress for Satisfactory: 47.83%/6180.04MB/01:11:01 Down: 0.96MB/s / Disk: 0MB/s

(15:57:59) INFO:    [Legendary]:        Progress for Satisfactory: 47.83%/6180.04MB/01:11:02 Down: 1.42MB/s / Disk: 0MB/s

(15:58:00) INFO:    [Legendary]:        Progress for Satisfactory: 47.85%/6182.47MB/01:11:02 Down: 1MB/s / Disk: 2MB/s

(15:58:01) INFO:    [Legendary]:        Progress for Satisfactory: 47.86%/6183.14MB/01:11:02 Down: 0.67MB/s / Disk: 0MB/s

(15:58:02) INFO:    [Legendary]:        Progress for Satisfactory: 47.87%/6185.03MB/01:11:03 Down: 1.89MB/s / Disk: 0MB/s

(15:58:03) INFO:    [Legendary]:        Progress for Satisfactory: 47.88%/6185.95MB/01:10:56 Down: 0.92MB/s / Disk: 9.99MB/s

(15:58:04) INFO:    [Legendary]:        Progress for Satisfactory: 47.89%/6186.88MB/01:10:57 Down: 0.94MB/s / Disk: 0MB/s

(15:58:07) INFO:    [Legendary]:        Progress for Satisfactory: 47.89%/6186.88MB/01:10:57 Down: 0MB/s / Disk: 0MB/s

(15:58:08) INFO:    [Legendary]:        Progress for Satisfactory: 47.89%/6187.70MB/01:10:59 Down: 0.81MB/s / Disk: 0MB/s

(15:58:09) INFO:    [Legendary]:        Progress for Satisfactory: 47.9%/6188.64MB/01:10:59 Down: 0.94MB/s / Disk: 0MB/s

(15:58:11) INFO:    [Legendary]:        Progress for Satisfactory: 47.9%/6188.64MB/01:11:00 Down: 0MB/s / Disk: 0MB/s

(15:58:12) INFO:    [Legendary]:        Progress for Satisfactory: 47.91%/6189.61MB/01:11:00 Down: 0.97MB/s / Disk: 1MB/s

(15:58:14) INFO:    [Legendary]:        Progress for Satisfactory: 47.91%/6189.61MB/01:11:01 Down: 0.94MB/s / Disk: 0MB/s

(15:58:15) INFO:    [Legendary]:        Progress for Satisfactory: 47.92%/6191.49MB/01:11:02 Down: 0.94MB/s / Disk: 0MB/s

(15:58:16) INFO:    [Legendary]:        Progress for Satisfactory: 47.93%/6192.40MB/01:11:02 Down: 0.91MB/s / Disk: 0MB/s

(15:58:17) INFO:    [Legendary]:        Progress for Satisfactory: 47.93%/6192.40MB/01:11:03 Down: 0MB/s / Disk: 0MB/s

(15:58:19) INFO:    [Legendary]:        Progress for Satisfactory: 47.93%/6192.40MB/01:11:03 Down: 0MB/s / Disk: 0MB/s

(15:58:20) INFO:    [Legendary]:        Progress for Satisfactory: 47.93%/6192.40MB/01:11:04 Down: 0MB/s / Disk: 0MB/s

(15:58:21) INFO:    [Legendary]:        Progress for Satisfactory: 47.94%/6193.22MB/01:11:00 Down: 0.82MB/s / Disk: 6.99MB/s

(15:58:22) INFO:    [Legendary]:        Progress for Satisfactory: 47.95%/6195.00MB/01:11:01 Down: 1.78MB/s / Disk: 0MB/s

(15:58:23) INFO:    [Legendary]:        Progress for Satisfactory: 47.96%/6195.95MB/01:11:01 Down: 0.95MB/s / Disk: 0MB/s

(15:58:27) INFO:    [Legendary]:        Progress for Satisfactory: 47.96%/6195.95MB/01:11:02 Down: 0MB/s / Disk: 0MB/s

(15:58:29) INFO:    [Legendary]:        Progress for Satisfactory: 47.96%/6195.95MB/01:11:04 Down: 0MB/s / Disk: 0MB/s

(15:58:31) INFO:    [Legendary]:        Progress for Satisfactory: 47.96%/6195.95MB/01:11:05 Down: 0.69MB/s / Disk: 1MB/s

(15:58:33) INFO:    [Legendary]:        Progress for Satisfactory: 47.96%/6196.64MB/01:11:05 Down: 1MB/s / Disk: 0MB/s

(15:58:34) INFO:    [Legendary]:        Progress for Satisfactory: 47.98%/6198.64MB/01:11:06 Down: 1MB/s / Disk: 0MB/s

(15:58:35) INFO:    [Legendary]:        Progress for Satisfactory: 47.98%/6199.54MB/01:11:07 Down: 0.9MB/s / Disk: 0MB/s

(15:58:36) INFO:    [Legendary]:        Progress for Satisfactory: 47.98%/6199.54MB/01:11:07 Down: 0MB/s / Disk: 0MB/s

(15:58:37) INFO:    [Legendary]:        Progress for Satisfactory: 47.98%/6199.54MB/01:11:08 Down: 0MB/s / Disk: 0MB/s

(15:58:38) INFO:    [Legendary]:        Progress for Satisfactory: 47.99%/6200.46MB/01:11:08 Down: 0.91MB/s / Disk: 0MB/s

(15:58:39) INFO:    [Legendary]:        Progress for Satisfactory: 48%/6201.38MB/01:11:09 Down: 0.92MB/s / Disk: 0MB/s

(15:58:41) INFO:    [Legendary]:        Progress for Satisfactory: 48%/6201.38MB/01:11:09 Down: 1.77MB/s / Disk: 0MB/s

(15:58:42) INFO:    [Legendary]:        Progress for Satisfactory: 48.01%/6203.15MB/01:11:10 Down: 0MB/s / Disk: 0MB/s

(15:58:43) INFO:    [Legendary]:        Progress for Satisfactory: 48.02%/6204.11MB/01:11:11 Down: 0.96MB/s / Disk: 0MB/s

(15:58:45) INFO:    [Legendary]:        Progress for Satisfactory: 48.02%/6204.11MB/01:11:11 Down: 0.92MB/s / Disk: 0MB/s

(15:58:47) INFO:    [Legendary]:        Progress for Satisfactory: 48.03%/6205.03MB/01:11:12 Down: 0MB/s / Disk: 0MB/s

(15:58:49) INFO:    [Legendary]:        Progress for Satisfactory: 48.03%/6205.03MB/01:11:13 Down: 1.95MB/s / Disk: 11.99MB/s

(15:58:50) INFO:    [Legendary]:        Progress for Satisfactory: 48.05%/6207.91MB/01:11:06 Down: 0.93MB/s / Disk: 0MB/s

(15:58:51) INFO:    [Legendary]:        Progress for Satisfactory: 48.05%/6207.91MB/01:11:07 Down: 0MB/s / Disk: 0MB/s

(15:58:52) INFO:    [Legendary]:        Progress for Satisfactory: 48.05%/6208.58MB/01:11:07 Down: 0.67MB/s / Disk: 0MB/s

(15:58:53) INFO:    [Legendary]:        Progress for Satisfactory: 48.06%/6209.52MB/01:11:08 Down: 0.95MB/s / Disk: 0MB/s

(15:58:54) INFO:    [Legendary]:        Progress for Satisfactory: 48.08%/6211.31MB/01:11:08 Down: 1.79MB/s / Disk: 0MB/s

(15:58:55) INFO:    [Legendary]:        Progress for Satisfactory: 48.09%/6213.44MB/01:11:09 Down: 2.13MB/s / Disk: 0MB/s

(15:58:56) INFO:    [Legendary]:        Progress for Satisfactory: 48.11%/6215.17MB/01:11:09 Down: 1.73MB/s / Disk: 0MB/s

(15:58:57) INFO:    [Legendary]:        Progress for Satisfactory: 48.12%/6216.67MB/01:11:10 Down: 1.49MB/s / Disk: 0MB/s

(15:58:58) INFO:    [Legendary]:        Progress for Satisfactory: 48.13%/6218.58MB/01:11:10 Down: 1.91MB/s / Disk: 0MB/s

(15:58:59) INFO:    [Legendary]:        Progress for Satisfactory: 48.15%/6221.30MB/01:11:11 Down: 2.72MB/s / Disk: 0MB/s

(15:59:00) INFO:    [Legendary]:        Progress for Satisfactory: 48.15%/6221.30MB/01:11:11 Down: 0MB/s / Disk: 0MB/s

(15:59:01) INFO:    [Legendary]:        Progress for Satisfactory: 48.18%/6224.22MB/01:11:02 Down: 2.92MB/s / Disk: 13.99MB/s
```

### Steps to reproduce

1. Install any game from the Epic Games library

### Expected behavior

Similar download speeds to the official Epic Games launcher

### Heroic Version

Latest Stable

### System Information

- OS: up-to-date Arch Linux, Heroic installed from the AUR

**Comment by BeiNacht** [comment]
Same issue. Running Heroic 2.15.2 on NixOS unstable
![image](https://github.com/user-attachments/assets/f9d2fdfc-baae-4a64-ac6b-ccdbece5f03d)

**Comment by BeiNacht** [comment]
@FreezyLemon after deleting the legendaryConfig folder it works again

```
14:46:45) INFO:    [Legendary]:        Progress for Ghostrunner: 6.47%/1242.25MB/00:08:39 Down: 42.61MB/s / Disk: 48.5MB/s
(14:46:46) INFO:    [Legendary]:        Progress for Ghostrunner: 6.74%/1293.38MB/00:08:33 Down: 51.12MB/s / Disk: 84.99MB/s
(14:46:47) INFO:    [Legendary]:        Progress for Ghostrunner: 6.97%/1336.94MB/00:08:25 Down: 43.55MB/s / Disk: 93.99MB/s
(14:46:48) INFO:    [Legendary]:        Progress for Ghostrunner: 7.14%/1369.48MB/00:08:25 Down: 32.54MB/s / Disk: 61.49MB/s
(14:46:49) INFO:    [Legendary]:        Progress for Ghostrunner: 7.29%/1399.90MB/00:08:23 Down: 30.41MB/s / Disk: 68.43MB/s
(14:46:50) INFO:    [Legendary]:        Progress for Ghostrunner: 7.5%/1439.70MB/00:08:24 Down: 39.79MB/s / Disk: 54.49MB/s
(14:46:51) INFO:    [Legendary]:        Progress for Ghostrunner: 7.75%/1488.19MB/00:08:22 Down: 48.48MB/s / Disk: 71.5MB/s
(14:46:52) INFO:    [Legendary]:        Progress for Ghostrunner: 7.96%/1528.34MB/00:08:23 Down: 40.14MB/s / Disk: 53.99MB/s
(14:46:53) INFO:    [Legendary]:        Progress for Ghostrunner: 8.2%/1572.93MB/00:08:20 Down: 44.58MB/s / Disk: 77MB/s
(14:46:54) INFO:    [Legendary]:        Progress for Ghostrunner: 8.42%/1616.32MB/00:08:22 Down: 43.37MB/s / Disk: 47.5MB/s
(14:46:55) INFO:    [Legendary]:        Progress for Ghostrunner: 8.65%/1660.01MB/00:08:21 Down: 43.68MB/s / Disk: 63.98MB/s
(14:46:56) INFO:    [Legendary]:        Progress for Ghostrunner: 8.85%/1699.28MB/00:08:19 Down: 39.27MB/s / Disk: 72.01MB/s
(14:46:57) INFO:    [Legendary]:        Progress for Ghostrunner: 9.09%/1745.05MB/00:08:21 Down: 45.75MB/s / Disk: 48.5MB/s
(14:46:58) INFO:    [Legendary]:        Progress for Ghostrunner: 9.3%/1784.74MB/00:08:18 Down: 39.68MB/s / Disk: 75.5MB/s
(14:46:59) INFO:    [Legendary]:        Progress for Ghostrunner: 9.47%/1817.20MB/00:08:19 Down: 32.45MB/s / Disk: 50.5MB/s
(14:47:00) INFO:    [Legendary]:        Progress for Ghostrunner: 9.68%/1858.17MB/00:08:20 Down: 40.95MB/s / Disk: 56.5MB/s
(14:47:01) INFO:    [Legendary]:        Progress for Ghostrunner: 9.89%/1897.53MB/00:08:19 Down: 39.35MB/s / Disk: 66.98MB/s
(14:47:02) INFO:    [Legendary]:        Progress for Ghostrunner: 10.07%/1932.01MB/00:08:20 Down: 34.47MB/s / Disk: 52MB/s
(14:47:03) INFO:    [Legendary]:        Progress for Ghostrunner: 10.25%/1966.91MB/00:08:21 Down: 34.89MB/s / Disk: 51.51MB/s
(14:47:04) INFO:    [Legendary]:        Progress for Ghostrunner: 10.43%/2002.20MB/00:08:21 Down: 35.28MB/s / Disk: 56.99MB/s
(14:47:05) INFO:    [Legendary]:        Progress for Ghostrunner: 10.61%/2035.54MB/00:08:20 Down: 33.34MB/s / Disk: 63.99MB/s
(14:47:06) INFO:    [Legendary]:        Progress for Ghostrunner: 10.79%/2070.46MB/00:08:21 Down: 34.91MB/s / Disk: 49.49MB/s
(14:47:07) INFO:    [Legendary]:        Progress for Ghostrunner: 10.95%/2100.71MB/00:08:24 Down: 30.24MB/s / Disk: 35.5MB/s
(14:47:08) INFO:    [Legendary]:        Progress for Ghostrunner: 11.11%/2133.05MB/00:08:22 Down: 32.33MB/s / Disk: 73.99MB/s
(14:47:09) INFO:    [Legendary]:        Progress for Ghostrunner: 11.31%/2171.42MB/00:08:22 Down: 38.36MB/s / Disk: 57MB/s
(14:47:10) INFO:    [Legendary]:        Progress for Ghostrunner: 11.56%/2217.91MB/00:08:18 Down: 46.48MB/s / Disk: 80.99MB/s
(14:47:11) INFO:    [Legendary]:        Progress for Ghostrunner: 11.77%/2258.38MB/00:08:14 Down: 40.46MB/s / Disk: 81.49MB/s
(14:47:12) INFO:    [Legendary]:        Progress for Ghostrunner: 11.99%/2301.79MB/00:08:12 Down: 43.39MB/s / Disk: 72.27MB/s
(14:47:13) INFO:    [Legendary]:        Progress for Ghostrunner: 12.17%/2336.17MB/00:08:14 Down: 34.37MB/s / Disk: 43.37MB/s
(14:47:14) INFO:    [Legendary]:        Progress for Ghostrunner: 12.34%/2367.75MB/00:08:15 Down: 31.58MB/s / Disk: 46.99MB/s
(14:47:15) INFO:    [Legendary]:        Progress for Ghostrunner: 12.54%/2406.10MB/00:08:15 Down: 38.35MB/s / Disk: 54.72MB/s
(14:47:16) INFO:    [Legendary]:        Progress for Ghostrunner: 12.78%/2453.31MB/00:08:16 Down: 47.19MB/s / Disk: 54.99MB/s
(14:47:17) INFO:    [Legendary]:        Progress for Ghostrunner: 13.01%/2496.93MB/00:08:12 Down: 43.61MB/s / Disk: 85.37MB/s
(14:47:18) INFO:    [Legendary]:        Progress for Ghostrunner: 13.18%/2530.13MB/00:08:06 Down: 33.19MB/s / Disk: 101.27MB/s
(14:47:19) INFO:    [Legendary]:        Progress for Ghostrunner: 13.44%/2579.84MB/00:08:03 Down: 49.69MB/s / Disk: 81.22MB/s
(14:47:20) INFO:    [Legendary]:        Progress for Ghostrunner: 13.65%/2618.69MB/00:08:00 Down: 38.84MB/s / Disk: 78.34MB/s
(14:47:21) INFO:    [Legendary]:        Progress for Ghostrunner: 13.85%/2658.81MB/00:07:59 Down: 40.1MB/s / Disk: 66.93MB/s
(14:47:22) INFO:    [Legendary]:        Progress for Ghostrunner: 14.06%/2698.50MB/00:07:54 Down: 39.68MB/s / Disk: 94.54MB/s
```

**Comment by mymro** [comment]
I have the same issue on a steam deck using bazzite. The download speed appears to be capped at around 1.5 MB/s. My normal speed is around 150MB/s

**Comment by mymro** [comment]
Fixed after a restart

**Comment by blipk** [comment]
Same issue here, very slow speeds over WiFi, switching to Ethernet gets back to full speed.

Steam has no issue with speeds over WiFi.

**Comment by johan-jnn** [comment]
I can confirm this on version 2.18.1 (flatpak).
Tried to dowload an 11Go game.

The speed was very good until the last gigabyte where the download & writing was very slow (< 1Mb/s for internet and < 5Mb/s for writing speed).

**Comment by johan-jnn** [comment]
It has been like this since the 80-90% of the game's download
<img width="1653" height="238" alt="Image" src="https://github.com/user-attachments/assets/7667c8eb-bd97-4bb2-a0fb-406897597e45" />

**Comment by realtimeafk** [comment]
Getting the same issue here, it wasn't like this before, though. 

disabled wifi and used ethernet only and issue persists - im getting 10mbps max (in burst no less) when my internet speed is closer to 200mbps

**Comment by dariusmiles2123** [comment]
My download speed are also at an average of 0.5 mbps which makes it unsustainable to dowload games through Heroic. I tried playing with the max number of workers, but it didn't seem to change anything, although I hadn't rebooted my computer.

**Comment by FramedStone** [comment]
> I can confirm this on version 2.18.1 (flatpak). Tried to dowload an 11Go game.
> 
> The speed was very good until the last gigabyte where the download & writing was very slow (< 1Mb/s for internet and < 5Mb/s for writing speed).

same here using `yay` , I'm using Ethernet and the download speeds spikes between 1-2 MB/s even after a full system reboot.

<img width="676" height="146" alt="Image" src="https://github.com/user-attachments/assets/fb56550a-8935-40d2-a804-5457ce455f94" />

**Comment by dance-monkey** [comment]
Also getting same, 0.5 MB/s, on Steam Deck, will try with an Ethernet adapter - not that that’s always practical with the Deck… :/

**Comment by apalazzi** [comment]
Also getting 0.5MB/s on desktop... downloading 77GB of game data will be veeeeeeeery long.

**Comment by source14** [comment]
Can also confirm this issue still exists, as mentioned above by BeiNacht, when I play around with the worker value at the bottom of the settings menu I can get expected speeds. I have a 2.5gb/s link and a 1gb/s fiber connection, and reducing my worker settings from "MAX" to "16" takes me from 0.4MB/s to a fully saturated link.

**Comment by uzayer** [comment]
same issue
