### ISSUE TITLE
Star Wars Battlefront 2 fails to launch

### ISSUE THREAD

**Issue by Skulduggerry** [Heroic-Games-Launcher/HeroicGamesLauncher#4563]
### Describe the bug

When trying to launch Star Wars Battlefront 2: Celebration Edition from the Epic Games store it always quits with the message 
`bwrap: Can't chdir to /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux: No such file or directory`

### Add logs

```text
Launching "STAR WARS™ Battlefront™ II: Celebration Edition" (legendary)
Native? No
Installed in: undefined

System Info:
CPU: 16x AMD Ryzen 7 3700X 8-Core Processor
Memory: 16.67 GB (used: 3.5 GB)
GPUs:
  GPU 0:
    Name: Advanced Micro Devices, Inc. [AMD/ATI] Navi 21 [Radeon RX 6800/6800 XT / 6900 XT]
    IDs: D=73bf V=1002 SD=3953 SV=1462
    Driver: amdgpu
OS: Arch Linux 6.14.7-arch2-1 (linux)

The current system is not a Steam Deck
We are running inside a Flatpak container

Software Versions:
  Heroic: 2.17.0 Cutty Flam Franky
  Legendary: 0.20.37 Exit 17 (Heroic)
  gogdl: 1.1.2
  comet: comet 0.2.0
  Nile: 1.1.2 Will A. Zeppeli

Game Settings: {
	"autoInstallDxvkNvapi": false,
	"preferSystemLibs": false,
	"enableEsync": true,
	"enableFsync": true,
	"nvidiaPrime": false,
	"enviromentOptions": [
		{
			"key": "MANGOHUD_CONFIGFILE",
			"value": "/home/felix/.dotfiles/.config/MangoHud/MangoHud.conf"
		}
	],
	"wrapperOptions": [],
	"showFps": false,
	"showMangohud": true,
	"useGameMode": true,
	"useSteamRuntime": true,
	"battlEyeRuntime": true,
	"eacRuntime": true,
	"language": "",
	"beforeLaunchScriptPath": "",
	"afterLaunchScriptPath": "",
	"verboseLogs": true,
	"disableUMU": false,
	"wineVersion": {
		"bin": "/home/felix/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/proton/GE-Proton-latest/proton",
		"name": "Proton - GE-Proton-latest",
		"type": "proton"
	},
	"winePrefix": "/home/felix/Games/Heroic/Prefixes/default/STAR WARS Battlefront II Celebration Edition"
}

Anticheat Status: Supported
Anticheats: ["FairFight"]

Game launched at: Sun May 25 2025 00:21:35 GMT+0200 (Central European Summer Time)

Winetricks packages: 

Launch Command: HEROIC_APP_NAME=MtMassive HEROIC_APP_RUNNER=legendary GAMEID=umu-0 HEROIC_APP_SOURCE=epic STORE=egs MANGOHUD_CONFIGFILE=/home/felix/.dotfiles/.config/MangoHud/MangoHud.conf LD_PRELOAD= STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/felix/.var/app/com.heroicgameslauncher.hgl/.steam/steam WINEPREFIX="/home/felix/Games/Heroic/Prefixes/default/STAR WARS Battlefront II Celebration Edition" STEAM_COMPAT_DATA_PATH="/home/felix/Games/Heroic/Prefixes/default/STAR WARS Battlefront II Celebration Edition" PROTONPATH=/home/felix/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/proton/GE-Proton-latest WINE_FULLSCREEN_FSR=0 PROTON_DISABLE_NVAPI=1 PROTON_EAC_RUNTIME=/home/felix/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/runtimes/eac_runtime PROTON_BATTLEYE_RUNTIME=/home/felix/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/runtimes/battleye_runtime STEAM_COMPAT_APP_ID=0 SteamAppId=0 SteamGameId=heroic-StarWarsBattlefront2 PROTON_LOG_DIR=/home/felix/.var/app/com.heroicgameslauncher.hgl WINEDEBUG=+fixme DXVK_LOG_LEVEL=info VKD3D_DEBUG=fixme /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary launch MtMassive --no-wine --wrapper "/usr/lib/extensions/vulkan/MangoHud/bin/mangohud --dlsym /app/bin/gamemoderun "/home/felix/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/runtimes/umu/umu_run.py"" --language en --origin

Game Log:
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
gamemodeauto: 
gamemodeauto: 
INFO: umu-launcher version 1.2.6 (3.12.10 (main, Nov 10 2011, 15:00:00) [GCC 14.2.0])
WARNING: Executable not found: start
INFO: steamrt3 is up to date
bwrap: Can't chdir to /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux: No such file or directory
============= End of log =============
```

### Steps to reproduce

1. install the game from your library
2. it should show the EA App installer
3. now try to launch the game
4. the game does not launch and the error above can be found in the logs

### Expected behavior

it should allow to install the game from the EA App and launch it

### Heroic Version

Latest Stable (Flatpak)

### System Information

- OS: Arch Linux x86_64
- Kernel: Linux 6.14.7
- Proton Version: GE-Proton10-3
- CPU: AMD Ryzen 7 3700x
- GPU: AMD Radeon RX 6800 XT
- RAM: 16 GB DDR4

**Comment by Po11da** [comment]
I had the same issue (flatpak, 2.17.0), but I was able to resolve it by following these steps:

1. Install the game through EA App.
2. Add `--dry-run` parameter and enable verbose logs.
3. The log will end with the following line:
`[cli] INFO: Origin launch command: /app/bin/gamemoderun /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/runtimes/umu/umu_run.py start 'link2ea://launchgame/MtMassive?AUTH_PASSWORD=49fj493jd93jd93dk&AUTH_TYPE=exchangecode&epicusername=EpicGamerNick&epicuserid=9e9493jj93939djnd&epiclocale=pl&theme=sws&platform=epic&Hotfix=go'` (note: this is not my actual login info)
5. Add game to the Heroic library with the following parameters:
- prefix is the same as for EA App/Battlefront 2
- executable is `/your/prefix/location/drive_c/Program Files/Electronic Arts/EA Desktop/EA Desktop/Link2EA.exe`
- in preferences, set link2ea obtained from logs as game argument:
`"link2ea://launchgame/MtMassive?AUTH_PASSWORD=49fj493jd93jd93dk&AUTH_TYPE=exchangecode&epicusername=EpicGamerNick&epicuserid=9e9493jj93939djnd&epiclocale=pl&theme=sws&platform=epic&Hotfix=go"`
Heroic will complain about incorrect placement of variables – ignore it.
6. Launching the newly added game will launch Battlefront 2.

Note: It seems that AUTH_PASSWORD is regenerated every time the game is launched – or at least it would seem so from my experience, although more thorough resting is required to confirm. This means that new link2ea url may have to be obtained for every launch from logs.

**Comment by roydbt** [comment]
I had the same problem, and when I looked at @Po11da 's solution I realized that what he had done was basically disable umu. So I tried doing just that on the original game (after installing it via the EA app) and it works.

**Comment by Skulduggerry** [comment]
Disabling umu at least results in the EA App showing up.
I will install the game and try if it runs later.

**Comment by Po11da** [comment]
TBH I just found random article online, which relied on article made back in the Origin days I followed most of the steps with some tweaks. At no point I knew what I was really doing or why it works, but I didn't want to bring the morale down.
Disabling umu launches the original game, no other modifications necessary. At first it started offline and couldn't connect to servers, but I'm not overly concerned since this issue occurs also on Windows and can only be fixed by closing the app. I was more concerned that it didn't want to launch at all on subsequent trials, but after switching few settings on and off/off and on again I was able to make it launch again… and subsequent launches work as well without additional fiddling. So it seems just disabling umu indeed works?

**Comment by Mystogab** [comment]
I "solved" this by not using Heroic. 
Installed Lutris and epic game store with wine GE-Proton10-3, I had to solve a bug where it keeps on eternal loop of updating and relunching (to fix it rename the directory adding idk like a 1 at the end, then change the executable path to match, launch once, close it, put back all same as before and it will lunch)
Then from there I just logged in, installed battlefront 2, and after a first login into EA launcher it works.
Some lunchs gives me 721 error I think it was, like it can connect to EA services but after a couple of retrials or closing and opening the game again worked. 
Playtrhough is pretty smooth and didnt notice any lag or anything network related.

**Comment by SilverDark6** [comment]
I have a similar issue to OP, I'm using Bazzite. Disabling umu in Heroic did not fix. I've tried this approach:

> I "solved" this by not using Heroic. Installed Lutris and epic game store with wine GE-Proton10-3, I had to solve a bug where it keeps on eternal loop of updating and relunching (to fix it rename the directory adding idk like a 1 at the end, then change the executable path to match, launch once, close it, put back all same as before and it will run) Then from there I just logged in, installed battlefront 2, and after a first login into EA launcher it works. Some times it gives me 721 error I think it was, like "it cann't connect to EA services" but after a couple of retrials or closing and opening the game again worked. Playtrhough is pretty smooth and didnt notice any lag or anything network related.

However, I'm unable to find a way to get the EA App from staying open while running under GE-Proton-10-x, hotfix, experimental, or GE-Proton-9.27. The EA App opens, I can sign in, and then moments later from the interface it crashes. The most stable way to have the EA App + Epic Games Store apps open at the same time seems to be using wine-10.8-staging-x86_64, and I was able to install Star Wars Battlefront 2 (2017) in this configuration, but the game is an unresponsive black screen with only a cursor and choppy sound playing when it runs. This is why I'm trying to run it using GE-Proton.

Curious if there's a known solution to what seems like the EA App intentionally not playing nicely with GE-Proton.

**Comment by PH4NT0K3N** [comment]
> I had the same issue (flatpak, 2.17.0), but I was able to resolve it by following these steps:
> 
>     1. Install the game through EA App.
> 
>     2. Add `--dry-run` parameter and enable verbose logs.
> 
>     3. The log will end with the following line:
>        `[cli] INFO: Origin launch command: /app/bin/gamemoderun /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/runtimes/umu/umu_run.py start 'link2ea://launchgame/MtMassive?AUTH_PASSWORD=49fj493jd93jd93dk&AUTH_TYPE=exchangecode&epicusername=EpicGamerNick&epicuserid=9e9493jj93939djnd&epiclocale=pl&theme=sws&platform=epic&Hotfix=go'` (note: this is not my actual login info)
> 
>     4. Add game to the Heroic library with the following parameters:
> 
> 
>     * prefix is the same as for EA App/Battlefront 2
> 
>     * executable is `/your/prefix/location/drive_c/Program Files/Electronic Arts/EA Desktop/EA Desktop/Link2EA.exe`
> 
>     * in preferences, set link2ea obtained from logs as game argument:
>       `"link2ea://launchgame/MtMassive?AUTH_PASSWORD=49fj493jd93jd93dk&AUTH_TYPE=exchangecode&epicusername=EpicGamerNick&epicuserid=9e9493jj93939djnd&epiclocale=pl&theme=sws&platform=epic&Hotfix=go"`
>       Heroic will complain about incorrect placement of variables – ignore it.
> 
> 
>     6. Launching the newly added game will launch Battlefront 2.
> 
> 
> Note: It seems that AUTH_PASSWORD is regenerated every time the game is launched – or at least it would seem so from my experience, although more thorough resting is required to confirm. This means that new link2ea url may have to be obtained for every launch from logs.

The log doesn't contain the link2ea stuff on my attempt. It just ends after `Game launched at: Sat Jun 07 2025 13:27:44 GMT+0200`.... And trying with the battlefrontii.exe instead of the link2ea.exe it gives me an error, saying origin is missing and needs to be installed: 

![Image](https://github.com/user-attachments/assets/e99cf955-82ff-4d27-ada3-297728e30fdd)

I have also tried with disabling umu and it results in the same. Anything I can try?

**Comment by Po11da** [comment]
Disabling umu and my old workaround no longer seem to work. I cannot launch EA App at all. Log from [EA App](https://0x0.st/86bo.log) and [Battlefront 2 with umu disabled](https://0x0.st/86bK.log).

**Comment by SilverDark6** [comment]
I've found a solution that seems to have survived contact with the Epic Games app updating. I was running into issues using Lutris with GE-Proton-X.XX, which winetricks seemed unable to solve due to how the 64 bit vs 32 bit prefixes are handled in Lutris. Steam has clearly solved this problem since you can run the game on the Steam Deck, so I followed @Mystogab's approach on Steam. 
**TL;DR:** Follow @Mystogab's approach, but with Steam instead of Lutris or Heroic.

I installed the Epic Games Store as a Steam app, and then proceeded to install Battlefront II from the Epic Games Store, which in turn will install the EA App (if you have the game through EGS). You need to do the trick where you rename the Win32 folder to break out of the endless app update loop. Then, change the **Target** and **Start In** fields to the SWBFII executable and the folder it's housed in. This will work until the next time the EGS app needs an update, at which point you'll need to repeat the process of renaming the Win32 folder, changing the **Target** and **Start In** fields back to the EGS app so it can update, and then back to SWBFII after the update is successful. It's kind of a headache but it seems to work.

Maybe there are some launch arguments out there that fix this endless EGS app update bug?

**Comment by djibux** [comment]
Strangely, disabling umu works for me in Desktop mode, but the game still fails to start in Game mode. EA pops up, tells me that the game failed to launch, and invites me to try again later.

**Comment by LloydNicholson** [comment]
Root cause, with a reproduction that isolates it to a single variable.

Same failure on Nobara 44 / KDE with **STAR WARS Zero Company** (Epic `app_name: bruno`, EA-App managed), Heroic 2.22.1 from the Terra RPM:

```
pressure-vessel-wrap: W: Unable to share
  "/usr/lib64/heroic/resources/app.asar.unpacked/build/bin/x64/linux"
  with container: Path "/usr" is reserved by the container framework
bwrap: Can't chdir to /usr/lib64/heroic/.../build/bin/x64/linux: No such file or directory
```

Identical to OP's `/app/bin/heroic/...` from the Flatpak, and to #4139 from COPR.

**Mechanism**

`callRunner` in `src/backend/launcher.ts` spawns the runner with

```ts
cwd: options?.cwd || runner.dir,
```

`runner.dir` is the directory of the bundled `legendary` binary. For a normal game legendary then chdirs into the game's install directory, so the cwd the wrapper inherits is harmless. For an EA-App/third-party title there is **no install record** (`Installed in: undefined` in OP's log), so nothing overrides it and `runner.dir` propagates all the way into `umu-run` → pressure-vessel → `bwrap`.

pressure-vessel refuses to bind-mount host paths under reserved prefixes (`/usr` for the RPM, `/app` for the Flatpak), so the cwd simply does not exist inside the container and bwrap aborts before Proton starts. That is why the AppImage is unaffected — its runner dir is `/tmp/.mount_HeroicXXXX/...`, which *is* shareable.

**A/B test isolating cwd** — same binary, same command, same prefix, only the cwd differs:

```
cd /usr/lib64/heroic/resources/app.asar.unpacked/build/bin/x64/linux
./legendary launch bruno --no-wine \
  --wrapper "/usr/bin/mangohud --dlsym /usr/bin/umu-run" --language en --origin
  -> bwrap: Can't chdir ...            # fails

cp legendary ~/.local/share/heroic-bins/ && cd ~/.local/share/heroic-bins
./legendary launch bruno ...  (identical otherwise)
  -> EA Desktop + SWZeroCompany.exe start normally   # works
```

**User-side workaround that keeps umu enabled**

Point *Settings → Advanced → Alternative Legendary Binary* at a symlink outside the reserved prefix:

```
mkdir -p ~/.local/share/heroic-bins
ln -s /usr/lib64/heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary \
      ~/.local/share/heroic-bins/legendary
```

`getLegendaryBin()` uses `dirname(altLegendaryBin)` as the cwd, so the cwd moves under `$HOME` while the binary still tracks package updates. Verified working. (Flatpak users would use a path under `~/.var/app/com.heroicgameslauncher.hgl/`.) This also explains why "disable UMU" helps — it removes pressure-vessel, and with it the reserved-path restriction.

**Suggested fix**

Don't leave the child's cwd inside Heroic's own install prefix when the launch goes through umu. Passing an explicit `cwd` (the install dir, the prefix, or `homedir()` as a fallback when `install_path` is undefined) would fix it for all three packaging formats at once.

Happy to test a patch.
