### ISSUE TITLE
Can not buy games anymore

### ISSUE THREAD

**Issue by Zorrototo** [Heroic-Games-Launcher/HeroicGamesLauncher#895]
**Describe the bug**
Trying to "buy" the latest free game Gods Will Fall result in two errors, First it warns the device is not supported, then when proceeding to confirm the order, it spit a red error message on top of the order page saying to verify my internet connection and retry later.

**Add Logs**

https://pastebin.com/FYCVDq1T

**To Reproduce**

1. Click Store menu link, scroll to the free game of the week, and click it
2. Click the GET button, a first error/warning occurs https://i.imgur.com/wBjyAJ0.jpg
3. Click CONTINUE button in the warning popup, and then click the CONFIRM ORDER button at the bottom, and accept the terms
4. Notice the order fails and a red error message appears on top of the order page https://i.imgur.com/Pn6qCNK.jpg

**Expected behavior**
Confirming the order should actually work and buy the game

**Desktop (please complete the following information):**

-  Heroic Version: 2.0.2 Roronoa Zoro
-  Legendary Version:  0.20.22 Anticitizen One (hotfix 3)
-  OS: ManjaroLinux KERNEL: 5.15.12-1-MANJARO ARCH: x64
-  CPU: AMD Ryzen 5 3600 6-Core Processor @3.6 GOVERNOR: powersave
-  RAM: Total: 16.8 GB Available: 9.72 GB
-  GRAPHICS: GPU0: NVIDIA GeForce GTX 1060 6GB VRAM: 6075MB DRIVER: 495.46 
-  PROTOCOL: x11

**Additional context**
After flooding request to try to buy the free game, I tried a workaround still within Heroic Games Launcher. I eventually was able to purchase the game, but only by doing the following:
- I scrolled to the bottom of the game page, and clicked the Support-A-Creator link
- It opened a Heroic Launcher new window, in which the Creator page loaded
- I scrolled down again, and click the EPIC logo, it brought me back in another new window to the EPIC Store home
- I then did the exact same thing as explained before, but it then worked properly (still had the warning about the device not supported though)
 
I was able to buy the free game like usual this way, and only this way (I tried a LOT the normal way withing the main Heroic Games Launcher window, I restarted the launcher multiple time to no available). The provided log is from this last session where I tried the normal way, and then succeeded with my little trick.

**Comment by flavioislima** [comment]
Hmm, it works fine for me (I see the device not supported message though). That red text looks like a error from the store itself.
But we changed the webview user agent here #836 so, if that was the issue, should be fixed on next version.

**Comment by Zorrototo** [comment]
Same thing today, it is BROKEN. I asked a friend of mine to try, he installed it from the AUR (same system as me, Manjaro KDE, Nvidia and Ryzen CPU), and actually he couldn't even login with Epic Games login, he could only login with SID. The Captcha always said we had wrong answers, I logout to try, and yes, I can not login anymore, Captcha is broken it says we give wrong answers. Only SID connection works.
Once my friend logged in with SID, he couldn't try to buy the current free game, as he was not logged in the Store within Heroic Games Launcher, he couldn't log in he spat the same error as on the initial Heroic Games Launcher login on first launch (wrong Captcha answers).

Try it, logout from your launcher, and try to login with Epic Games credentials. It doesn't work for me, it doesn't work for someone I just asked to install Heroic Games Launcher for a test. Issue may be on Manjaro globally, but for sure it doesn't work.



Pretty sure both issues are related. the broken login, and the broken

**Comment by Zorrototo** [comment]
Here is what happens, when you try to login to the Store: https://i.imgur.com/Hv5DxsD.jpg
Same thing if you logout from Heroic Games Launcher and try to login with Epic credentials.

And the initial issue described in the initial post is still the same situation, before I logged out from Heroic and the Store, now I can't continue testing as I can't re login to the Store within Heroic now.

**Comment by Zorrototo** [comment]
Here is a log, where I tried to login with my Epic credential to Heroic Games Launcher (I logged out completely and restarted Heroic for this log):  https://pastebin.com/qyF9QYFM

**Comment by flavioislima** [comment]
I will make some tests tomorrow. Might be related with some setting on the Webview.
